<section id="overview" class="space-y-5" data-overview-console>
    @php
        $visibleLateCount = $lateStudentsToday->count();
        $overviewCourses = $absentStudentsToday->concat($lateStudentsToday)->pluck('curso')->filter()->unique()->sort()->values();
        $overviewStatusMeta = [
            'online' => ['Conectado', 'bg-emerald-400', 'text-emerald-400'],
            'delayed' => ['Advertencia', 'bg-amber-400', 'text-amber-400'],
            'offline' => ['Sin comunicación', 'bg-rose-400', 'text-rose-400'],
            'never_connected' => ['Sin comunicación', 'bg-rose-400', 'text-rose-400'],
            'pending_assignment' => ['Pendiente', 'bg-sky-400', 'text-sky-400'],
            'inactive' => ['Inactivo', 'bg-slate-400', 'text-slate-400'],
        ];
    @endphp

    <header class="flex flex-col gap-4 rounded-2xl border border-slate-800 bg-slate-900 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
        <div><p class="text-[11px] font-black uppercase tracking-[.2em] text-teal-400">Centro de operaciones</p><h1 class="mt-1 text-2xl font-black text-white">Asistencia de hoy</h1><p class="mt-1 text-sm text-slate-400">{{ $activeSchool?->name ?? 'Red de centros educativos' }} · {{ $analysisDate->locale('es')->isoFormat('D [de] MMMM [de] YYYY') }}</p></div>
        <div class="flex flex-wrap items-center gap-2"><span class="inline-flex items-center gap-2 rounded-lg bg-emerald-400/10 px-3 py-2 text-xs font-black text-emerald-300"><span class="h-2 w-2 animate-pulse rounded-full bg-emerald-400"></span>Monitoreo activo</span>@if ($shareSchool?->public_dashboard_token)<a class="inline-flex items-center gap-2 rounded-lg bg-teal-500 px-3 py-2 text-xs font-black text-slate-950 hover:bg-teal-400" href="{{ route('public.dashboard.show', $shareSchool->public_dashboard_token) }}" target="_blank" rel="noopener">Abrir visualización <span aria-hidden="true">↗</span></a>@endif</div>
    </header>

    <section class="grid grid-cols-2 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm lg:grid-cols-4 dark:border-slate-800 dark:bg-slate-900" aria-label="Resumen de asistencia">
        @foreach ([
            ['students', 'Estudiantes', $resumen['total_estudiantes'], 'text-sky-600 dark:text-sky-400', 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2'],
            ['present', 'Presentes', $resumen['presentes_hoy'], 'text-emerald-600 dark:text-emerald-400', 'm5 12 4 4L19 6'],
            ['late', 'Tardanzas recientes', $visibleLateCount, 'text-amber-600 dark:text-amber-400', 'M12 8v4l3 2m6-2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z'],
            ['absent', 'Ausentes', $resumen['ausentes_hoy'], 'text-rose-600 dark:text-rose-400', 'M6 18 18 6M6 6l12 12'],
        ] as [$key, $label, $value, $color, $icon])
            <button class="border-stone-200 px-4 py-4 text-left transition hover:bg-stone-50 even:border-l lg:border-l lg:first:border-l-0 dark:border-slate-800 dark:hover:bg-slate-800/50" type="button" data-open-dialog="overview-{{ $key }}-dialog"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-slate-500 dark:text-slate-400">{{ $label }}</p><p class="mt-1 text-3xl font-black tabular-nums {{ $color }}">{{ number_format($value) }}</p></div><svg class="h-5 w-5 text-slate-300 dark:text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="{{ $icon }}"/></svg></div><p class="mt-1 text-[11px] text-slate-400">Ver detalle · {{ now()->format('H:i') }}</p></button>
        @endforeach
    </section>

    @foreach ([
        ['students', 'Matrícula estudiantil', $resumen['total_estudiantes'], $overviewGenderSummary['female'], $overviewGenderSummary['male'], 'Total de estudiantes activos'],
        ['present', 'Asistencia de hoy', $resumen['presentes_hoy'], $overviewGenderSummary['present_female'], $overviewGenderSummary['present_male'], 'Estudiantes con entrada registrada'],
    ] as [$key, $title, $total, $female, $male, $description])
        <dialog id="overview-{{ $key }}-dialog" class="m-auto w-[min(640px,94vw)] overflow-hidden rounded-3xl border-0 bg-white p-0 text-slate-900 shadow-2xl backdrop:bg-slate-950/80 dark:bg-slate-900 dark:text-slate-100"><header class="bg-slate-950 px-6 py-5 text-white"><div class="flex items-start justify-between"><div><p class="text-[11px] font-black uppercase tracking-[.2em] text-teal-400">Resumen oficial</p><h2 class="mt-1 text-2xl font-black">{{ $title }}</h2><p class="mt-1 text-sm text-slate-400">{{ $description }}</p></div><button class="rounded-full bg-white/10 px-3 py-2 text-xl hover:bg-white/20" type="button" data-close-dialog>×</button></div></header><div class="p-6"><div class="rounded-2xl bg-teal-50 p-5 text-center dark:bg-teal-400/10"><p class="text-xs font-black uppercase tracking-wider text-teal-700 dark:text-teal-300">Total</p><p class="mt-1 text-5xl font-black text-teal-700 dark:text-teal-300">{{ number_format($total) }}</p></div><div class="mt-4 grid grid-cols-2 gap-4"><div class="rounded-2xl border border-fuchsia-100 bg-fuchsia-50 p-5 dark:border-fuchsia-900 dark:bg-fuchsia-400/10"><p class="text-xs font-black uppercase text-fuchsia-700 dark:text-fuchsia-300">Hembras</p><p class="mt-2 text-4xl font-black text-fuchsia-700 dark:text-fuchsia-300">{{ number_format($female) }}</p></div><div class="rounded-2xl border border-sky-100 bg-sky-50 p-5 dark:border-sky-900 dark:bg-sky-400/10"><p class="text-xs font-black uppercase text-sky-700 dark:text-sky-300">Varones</p><p class="mt-2 text-4xl font-black text-sky-700 dark:text-sky-300">{{ number_format($male) }}</p></div></div>@if ($key === 'students' && $overviewGenderSummary['unspecified'] > 0)<p class="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-xs font-bold text-amber-700">{{ $overviewGenderSummary['unspecified'] }} estudiante(s) aún no tienen sexo asignado.</p>@endif</div></dialog>
    @endforeach

    @foreach ([['late', 'Estudiantes con tardanza', $lateStudentsToday, 'text-amber-400', 'bg-amber-100 text-amber-700'], ['absent', 'Estudiantes que no asistieron', $absentStudentsToday, 'text-rose-400', 'bg-rose-100 text-rose-700']] as [$key, $title, $roster, $headingColor, $badgeColor])
        <dialog id="overview-{{ $key }}-dialog" class="m-auto max-h-[90vh] w-[min(860px,95vw)] overflow-hidden rounded-3xl border-0 bg-white p-0 text-slate-900 shadow-2xl backdrop:bg-slate-950/80 dark:bg-slate-900 dark:text-slate-100" data-overview-roster data-{{ $key }}-students-dialog>
            <header class="bg-slate-950 px-6 py-5 text-white"><div class="flex items-start justify-between gap-4"><div><p class="text-[11px] font-black uppercase tracking-[.2em] {{ $headingColor }}">Seguimiento del día</p><h2 class="mt-1 text-2xl font-black">{{ $title }}</h2><p class="mt-1 text-sm text-slate-400">{{ $analysisDate->locale('es')->isoFormat('D [de] MMMM [de] YYYY') }} · {{ $roster->count() }} estudiante(s)</p></div><button class="rounded-full bg-white/10 px-3 py-2 text-xl hover:bg-white/20" type="button" data-close-dialog>×</button></div></header>
            <div class="border-b border-stone-200 bg-stone-50 p-4 dark:border-slate-800 dark:bg-slate-950"><div class="grid gap-3 sm:grid-cols-[1fr_220px]"><label class="relative"><span class="sr-only">Buscar estudiante</span><input class="w-full rounded-xl border border-stone-200 bg-white px-4 py-3 text-sm outline-none focus:border-teal-500 dark:border-slate-700 dark:bg-slate-900" type="search" placeholder="Buscar por nombre o matrícula..." data-roster-search></label><label><span class="sr-only">Filtrar por curso</span><select class="w-full rounded-xl border border-stone-200 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-900" data-roster-course><option value="">Todos los cursos</option>@foreach ($overviewCourses as $course)<option value="{{ Str::lower($course) }}">{{ $course }}</option>@endforeach</select></label></div></div>
            <div class="max-h-[58vh] overflow-y-auto p-4"><div class="grid gap-3 sm:grid-cols-2">@foreach ($roster as $student)<article class="rounded-2xl border border-stone-200 p-4 transition dark:border-slate-700" data-roster-row data-roster-course-value="{{ Str::lower($student->curso ?? '') }}" data-roster-search-value="{{ Str::lower($student->nombre.' '.$student->apellido.' '.$student->matricula) }}"><div class="flex items-start justify-between gap-3"><div class="flex min-w-0 items-center gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-sm font-black {{ $badgeColor }}">{{ Str::upper(Str::substr($student->nombre, 0, 1).Str::substr($student->apellido, 0, 1)) }}</span><div class="min-w-0"><h3 class="truncate font-black">{{ $student->nombre }} {{ $student->apellido }}</h3><p class="mt-1 truncate text-xs text-slate-500">{{ $student->matricula }} · {{ $student->curso }}</p></div></div><span class="rounded-full px-2.5 py-1 text-[10px] font-black uppercase {{ $badgeColor }}">{{ $key === 'late' ? 'Tardanza' : 'Ausente' }}</span></div><div class="mt-3 border-t border-stone-100 pt-3 text-xs text-slate-500 dark:border-slate-800"><span>{{ $student->sexo ?: 'Sexo no indicado' }}</span><span class="mx-2">·</span><span>{{ $student->father_email ?: $student->mother_email ?: 'Sin correo registrado' }}</span></div></article>@endforeach</div><p class="hidden p-10 text-center text-sm text-slate-500" data-roster-empty>No hay estudiantes que coincidan con los filtros.</p>@if ($roster->isEmpty())<p class="p-10 text-center text-sm text-slate-500">No hay estudiantes en esta condición.</p>@endif</div>
        </dialog>
    @endforeach

    <section class="grid gap-5 xl:grid-cols-12">
        @if (false)
        <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm xl:col-span-7 dark:border-slate-800 dark:bg-slate-900">
            <header class="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-4 dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-emerald-600 dark:text-emerald-400">Flujo de entradas</p><h2 class="mt-1 text-lg font-black">Actividad en vivo</h2></div><span class="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-black text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><span class="h-2 w-2 animate-pulse rounded-full bg-emerald-500"></span>Recibiendo</span></header>
            <div class="divide-y divide-stone-100 dark:divide-slate-800">
                @forelse ($ultimosRegistros->take(6) as $registro)
                    <div class="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4 px-5 py-3"><time class="font-mono text-sm font-black text-teal-600 dark:text-teal-300">{{ $registro['hora'] }}</time><div class="min-w-0"><p class="truncate text-sm font-black">{{ $registro['nombre'] }}</p><p class="mt-0.5 truncate text-xs text-slate-500">{{ $registro['curso'] }} · {{ $registro['lector'] }}</p></div><span class="rounded-full px-2.5 py-1 text-[11px] font-black {{ $registro['is_late'] ? 'bg-amber-100 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300' : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300' }}">{{ $registro['is_late'] ? 'Tardanza' : $registro['tipo'] }}</span></div>
                @empty
                    <p class="px-5 py-12 text-center text-sm text-slate-500">Aún no se han recibido registros hoy.</p>
                @endforelse
            </div>
        </article>
        @endif

        <article class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm xl:col-span-12 dark:border-slate-800 dark:bg-slate-900">
            <div class="flex items-start justify-between gap-4"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-sky-600 dark:text-sky-400">Infraestructura</p><h2 class="mt-1 text-lg font-black">Estado de lectores</h2></div><a class="text-xs font-black text-teal-600 hover:text-teal-500 dark:text-teal-300" href="{{ route($dashboardPageRoute, 'devices') }}">Administrar →</a></div>
            <div class="mt-4 grid grid-cols-2 gap-2"><div class="rounded-xl bg-emerald-50 px-3 py-3 dark:bg-emerald-400/10"><p class="text-xs font-bold text-emerald-700 dark:text-emerald-300">En línea</p><p class="mt-1 text-2xl font-black text-emerald-700 dark:text-emerald-300">{{ $deviceSummary['online'] }}</p></div><div class="rounded-xl bg-rose-50 px-3 py-3 dark:bg-rose-400/10"><p class="text-xs font-bold text-rose-700 dark:text-rose-300">Sin comunicación</p><p class="mt-1 text-2xl font-black text-rose-700 dark:text-rose-300">{{ $deviceSummary['offline'] }}</p></div></div>
            <div class="mt-4 grid gap-x-6 sm:grid-cols-2 xl:grid-cols-3">@forelse ($devices->take(6) as $device)@php([$readerLabel, $readerDot, $readerText] = $overviewStatusMeta[$device->connectionStatus()])<div class="flex items-center justify-between gap-4 border-t border-stone-100 py-3 dark:border-slate-800"><div class="min-w-0"><p class="truncate text-sm font-bold">{{ $device->name }}</p><p class="mt-0.5 truncate text-[11px] text-slate-400">{{ $device->location ?: $device->school?->short_name ?: $device->school?->name }}</p></div><div class="shrink-0 text-right"><span class="inline-flex items-center gap-1.5 text-[10px] font-black uppercase {{ $readerText }}"><span class="h-2 w-2 rounded-full {{ $readerDot }}"></span>{{ $readerLabel }}</span><p class="mt-1 text-[10px] text-slate-400">{{ $device->last_seen_at?->diffForHumans() ?? 'Nunca' }}</p></div></div>@empty<p class="py-8 text-center text-sm text-slate-500">No hay lectores registrados.</p>@endforelse</div>
        </article>
    </section>

    <section class="grid gap-5 xl:grid-cols-12">
        <article id="reports" class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm xl:col-span-7 dark:border-slate-800 dark:bg-slate-900"><header class="flex items-start justify-between border-b border-stone-100 p-5 dark:border-slate-800"><div><h2 class="text-lg font-black">Asistencia por curso</h2><p class="mt-1 text-sm text-slate-500">Desglose oficial por sexo y estudiantes presentes.</p></div><span class="rounded-full bg-teal-50 px-3 py-1.5 text-xs font-black text-teal-700 dark:bg-teal-400/10 dark:text-teal-300">{{ $resumen['porcentaje_hoy'] }}% general</span></header><div class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($asistenciaPorCurso as $curso)<section class="p-5"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="font-black">{{ $curso['curso'] }}</h3><p class="mt-1 text-xs text-slate-500">{{ $curso['presentes'] }} de {{ $curso['estudiantes'] }} presentes · {{ $curso['porcentaje'] }}%</p></div><div class="grid grid-cols-2 gap-2"><div class="rounded-xl bg-fuchsia-50 px-3 py-2 text-center dark:bg-fuchsia-400/10"><p class="text-[10px] font-black uppercase text-fuchsia-700 dark:text-fuchsia-300">Hembras</p><p class="mt-0.5 text-sm font-black text-fuchsia-700 dark:text-fuchsia-300">{{ $curso['present_female'] }}/{{ $curso['female'] }}</p></div><div class="rounded-xl bg-sky-50 px-3 py-2 text-center dark:bg-sky-400/10"><p class="text-[10px] font-black uppercase text-sky-700 dark:text-sky-300">Varones</p><p class="mt-0.5 text-sm font-black text-sky-700 dark:text-sky-300">{{ $curso['present_male'] }}/{{ $curso['male'] }}</p></div></div></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-stone-100 dark:bg-slate-800"><div class="h-full rounded-full bg-teal-500" style="width: {{ $curso['porcentaje'] }}%"></div></div></section>@empty<p class="p-8 text-center text-sm text-slate-500">Aún no hay estudiantes registrados.</p>@endforelse</div></article>

        <article class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm xl:col-span-5 dark:border-slate-800 dark:bg-slate-900"><div class="flex items-start justify-between gap-4"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600 dark:text-teal-400">Pantalla institucional</p><h2 class="mt-1 text-lg font-black">Enlace público</h2></div>@if ($shareSchool?->public_dashboard_token)<a class="rounded-lg bg-teal-600 px-3 py-2 text-xs font-black text-white" href="{{ route('public.dashboard.show', $shareSchool->public_dashboard_token) }}" target="_blank" rel="noopener">Abrir visualización ↗</a>@endif</div>
            @if ($shareSchool)
                @if ($shareSchool->public_dashboard_token)
                    @php($publicDashboardUrl = route('public.dashboard.show', $shareSchool->public_dashboard_token))
                    <input class="mt-4 w-full rounded-lg border border-stone-200 bg-stone-50 px-3 py-2.5 font-mono text-[11px] dark:border-slate-700 dark:bg-slate-950" value="{{ $publicDashboardUrl }}" readonly onclick="this.select()">
                    <div class="mt-3 flex gap-2"><form action="{{ route('schools.public-dashboard.generate', $shareSchool) }}" method="POST">@csrf<button class="rounded-lg px-3 py-2 text-xs font-bold text-slate-600 ring-1 ring-inset ring-stone-200 dark:text-slate-300 dark:ring-slate-700" type="submit">Regenerar</button></form><form action="{{ route('schools.public-dashboard.revoke', $shareSchool) }}" method="POST">@csrf @method('DELETE')<button class="rounded-lg px-3 py-2 text-xs font-bold text-rose-600 ring-1 ring-inset ring-rose-200 dark:text-rose-300 dark:ring-rose-900" type="submit">Desactivar</button></form></div>
                @else
                    <p class="mt-3 text-sm text-slate-500">Genera un enlace seguro para la pantalla de dirección.</p><form class="mt-4" action="{{ route('schools.public-dashboard.generate', $shareSchool) }}" method="POST">@csrf<button class="rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-black text-white" type="submit">Generar enlace público</button></form>
                @endif
            @else
                <p class="mt-3 text-sm text-slate-500">Selecciona una escuela para administrar su visualización.</p>
            @endif
        </article>
    </section>

    <article class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-black">Tendencia semanal</h2><p class="mt-1 text-sm text-slate-500">Porcentaje de estudiantes presentes durante los últimos cinco días.</p></div><span class="rounded-lg bg-teal-50 px-3 py-2 text-xs font-black text-teal-700 dark:bg-teal-400/10 dark:text-teal-300">5 días</span></div>
        <div class="mt-6 grid h-44 grid-cols-5 items-end gap-3 sm:h-52 sm:gap-6">
            @foreach ($tendenciaSemanal as $dia)
                <div class="flex h-full min-w-0 flex-col justify-end text-center"><p class="mb-2 text-xs font-black tabular-nums text-slate-700 dark:text-slate-200">{{ $dia['porcentaje'] }}%</p><div class="flex h-28 items-end overflow-hidden rounded-t-lg bg-stone-100 sm:h-36 dark:bg-slate-800"><div class="w-full rounded-t-lg bg-teal-500" style="height: {{ max($dia['porcentaje'], 4) }}%"></div></div><p class="mt-2 text-xs font-black uppercase text-slate-600 dark:text-slate-300">{{ $dia['dia'] }}</p><p class="mt-0.5 text-[11px] text-slate-400">{{ $dia['fecha'] }}</p></div>
            @endforeach
        </div>
    </article>
</section>
