<section id="attendance" class="space-y-5" data-live-attendance-console>
    <header class="flex flex-col gap-4 border-b border-stone-200 pb-5 sm:flex-row sm:items-end sm:justify-between dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.2em] text-emerald-500">Operación en tiempo real</p><h1 class="mt-1 text-2xl font-black tracking-tight">Actividad en vivo</h1><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Lecturas de asistencia recibidas hoy desde los dispositivos de la institución.</p></div><span class="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-100 px-3 py-2 text-xs font-black text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><span class="h-2.5 w-2.5 animate-pulse rounded-full bg-emerald-500"></span>Captura activa</span></header>

    <section class="grid grid-cols-2 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm lg:grid-cols-4 dark:border-slate-800 dark:bg-slate-900">
        @foreach ([['Estudiantes', $attendanceRosterSummary['total'], 'text-sky-500'], ['Presentes', $attendanceRosterSummary['present'], 'text-emerald-500'], ['Tardanzas', $attendanceRosterSummary['late'], 'text-amber-500'], ['Ausentes', $attendanceRosterSummary['absent'], 'text-rose-500']] as [$label, $value, $color])
            <article class="border-stone-200 px-4 py-4 even:border-l lg:border-l lg:first:border-l-0 dark:border-slate-800"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-1 text-3xl font-black {{ $color }}">{{ $value }}</p></article>
        @endforeach
    </section>

    <article class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <form class="grid gap-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] sm:items-end" method="GET" action="{{ route($dashboardPageRoute, 'attendance') }}">
            @if ($selectedSchoolId && ($usuario['role'] ?? null) === 'superadmin')<input type="hidden" name="school_id" value="{{ $selectedSchoolId }}">@endif
            <label class="text-xs font-black uppercase tracking-wider text-slate-500">Curso
                <select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="course">
                    <option value="">Todos los cursos</option>
                    @foreach ($attendanceCourses as $course)<option value="{{ $course }}" @selected($selectedCourse === $course)>{{ $course }}</option>@endforeach
                </select>
            </label>
            <label class="text-xs font-black uppercase tracking-wider text-slate-500">Estado
                <select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="attendance_status">
                    @foreach (['all' => 'Todos', 'present' => 'Presentes', 'late' => 'Tardanzas', 'absent' => 'Ausentes'] as $value => $label)<option value="{{ $value }}" @selected($attendanceStatus === $value)>{{ $label }}</option>@endforeach
                </select>
            </label>
            <button class="rounded-xl bg-teal-600 px-5 py-3 text-sm font-black text-white hover:bg-teal-500" type="submit">Aplicar filtros</button>
        </form>
    </article>

    <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" data-attendance-roster-status="{{ $attendanceStatus }}">
        <header class="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-4 dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600 dark:text-teal-400">Resumen del curso</p><h2 class="mt-1 text-lg font-black">Estudiantes por estado</h2></div><span class="rounded-full bg-stone-100 px-3 py-1.5 text-xs font-black text-slate-600 dark:bg-slate-800 dark:text-slate-300">{{ $attendanceRoster->count() }} visibles</span></header>
        <div class="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3">
            @forelse ($attendanceRoster as $student)
                @php($statusStyle = match ($student['status']) { 'late' => ['Tardanza', 'bg-amber-50 text-amber-700 ring-amber-200 dark:bg-amber-400/10 dark:text-amber-300 dark:ring-amber-900'], 'absent' => ['Ausente', 'bg-rose-50 text-rose-700 ring-rose-200 dark:bg-rose-400/10 dark:text-rose-300 dark:ring-rose-900'], default => ['Presente', 'bg-emerald-50 text-emerald-700 ring-emerald-200 dark:bg-emerald-400/10 dark:text-emerald-300 dark:ring-emerald-900'] })
                <div class="flex items-center justify-between gap-3 rounded-xl border border-stone-100 p-4 dark:border-slate-800">
                    <div class="min-w-0"><p class="truncate text-sm font-black">{{ $student['nombre'] }}</p><p class="mt-1 truncate text-xs text-slate-500">{{ $student['curso'] }} · {{ $student['matricula'] }}</p></div>
                    <div class="text-right"><span class="inline-flex rounded-full px-2.5 py-1 text-[10px] font-black ring-1 {{ $statusStyle[1] }}">{{ $statusStyle[0] }}</span>@if ($student['hora'])<p class="mt-1 font-mono text-[11px] text-slate-400">{{ $student['hora'] }}</p>@endif</div>
                </div>
            @empty
                <p class="py-10 text-center text-sm text-slate-500 sm:col-span-2 xl:col-span-3">No hay estudiantes para los filtros seleccionados.</p>
            @endforelse
        </div>
    </article>

    <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <header class="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-4 dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-sky-600 dark:text-sky-400">Registros del día</p><h2 class="mt-1 text-lg font-black">Lecturas recibidas</h2></div><span class="rounded-full bg-stone-100 px-3 py-1.5 text-xs font-black text-slate-600 dark:bg-slate-800 dark:text-slate-300">{{ $ultimosRegistros->count() }} registros</span></header>
        <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[880px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Hora</th><th class="px-5 py-3">Estudiante</th><th class="px-5 py-3">Curso</th><th class="px-5 py-3">Lector</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3 text-right">Observación</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($ultimosRegistros as $registro)<tr class="hover:bg-stone-50/70 dark:hover:bg-slate-800/40"><td class="px-5 py-4 font-mono text-base font-black text-teal-600 dark:text-teal-300">{{ $registro['hora'] }}</td><td class="px-5 py-4"><p class="text-sm font-black">{{ $registro['nombre'] }}</p><p class="mt-0.5 font-mono text-[11px] text-slate-400">{{ $registro['matricula'] }}</p></td><td class="px-5 py-4 text-sm font-semibold text-slate-600 dark:text-slate-300">{{ $registro['curso'] }}</td><td class="px-5 py-4"><p class="text-sm font-bold">{{ $registro['lector'] }}</p>@if ($registro['escuela'])<p class="mt-0.5 text-[11px] text-slate-400">{{ $registro['escuela'] }}</p>@endif</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1.5 text-[11px] font-black {{ $registro['is_late'] ? 'bg-amber-100 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300' : ($registro['tipo'] === 'Entrada' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300' : 'bg-sky-100 text-sky-700 dark:bg-sky-400/10 dark:text-sky-300') }}">{{ $registro['is_late'] ? 'Tardanza' : $registro['tipo'] }}</span></td><td class="px-5 py-4 text-right">@if ($registro['excuse_type'])<span class="text-xs font-black text-sky-600 dark:text-sky-300">Justificada</span><p class="mt-1 text-xs text-slate-500">{{ $registro['excuse_note'] }}</p>@elseif ($registro['is_late'] || $registro['is_early_departure'])<details class="relative inline-block text-left"><summary class="cursor-pointer list-none text-xs font-black text-amber-600">Justificar</summary><form class="absolute right-0 z-20 mt-2 grid w-64 gap-2 rounded-xl border border-stone-200 bg-white p-3 text-left shadow-xl dark:border-slate-700 dark:bg-slate-900" action="{{ route('attendances.excuses.store', $registro['id']) }}" method="POST">@csrf<input type="hidden" name="excuse_type" value="{{ $registro['is_late'] ? 'late' : 'early_departure' }}"><textarea class="rounded-lg border border-stone-200 bg-stone-50 p-2 text-xs dark:border-slate-700 dark:bg-slate-950" name="excuse_note" required placeholder="Motivo de la excusa"></textarea><button class="rounded-lg bg-teal-600 px-3 py-2 text-xs font-black text-white" type="submit">Guardar justificación</button></form></details>@else<span class="text-xs font-bold text-slate-400">Sin alertas</span>@endif</td></tr>@empty<tr><td class="px-6 py-16 text-center text-sm text-slate-500" colspan="6">Esperando el primer registro de hoy.</td></tr>@endforelse</tbody></table></div>
        <div class="divide-y divide-stone-100 md:hidden dark:divide-slate-800">@forelse ($ultimosRegistros as $registro)<div class="grid grid-cols-[auto_1fr_auto] items-center gap-3 px-4 py-4"><time class="font-mono text-sm font-black text-teal-500">{{ substr($registro['hora'], 0, 5) }}</time><div class="min-w-0"><p class="truncate text-sm font-black">{{ $registro['nombre'] }}</p><p class="mt-0.5 truncate text-xs text-slate-500">{{ $registro['curso'] }} · {{ $registro['lector'] }}</p></div><span class="text-[10px] font-black {{ $registro['is_late'] ? 'text-amber-500' : 'text-emerald-500' }}">{{ $registro['is_late'] ? 'TARDANZA' : strtoupper($registro['tipo']) }}</span></div>@empty<p class="px-5 py-14 text-center text-sm text-slate-500">Esperando el primer registro de hoy.</p>@endforelse</div>
    </article>
</section>
