<section id="attendance" class="space-y-5" data-live-attendance-console>
    <header class="flex flex-col gap-4 border-b border-stone-200 pb-5 sm:flex-row sm:items-end sm:justify-between dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.2em] text-emerald-500">Operación en tiempo real</p><h1 class="mt-1 text-2xl font-black tracking-tight">Actividad en vivo</h1><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Lecturas de asistencia recibidas hoy desde los dispositivos de la institución.</p></div><span class="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-100 px-3 py-2 text-xs font-black text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><span class="h-2.5 w-2.5 animate-pulse rounded-full bg-emerald-500"></span>Captura activa</span></header>

    <section class="grid grid-cols-2 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm lg:grid-cols-4 dark:border-slate-800 dark:bg-slate-900">
        @foreach ([['Registros visibles', $ultimosRegistros->count(), 'text-sky-500'], ['Entradas', $ultimosRegistros->where('tipo', 'Entrada')->count(), 'text-emerald-500'], ['Tardanzas', $ultimosRegistros->where('is_late', true)->count(), 'text-amber-500'], ['Salidas', $ultimosRegistros->where('tipo', 'Salida')->count(), 'text-teal-500']] as [$label, $value, $color])
            <article class="border-stone-200 px-4 py-4 even:border-l lg:border-l lg:first:border-l-0 dark:border-slate-800"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-1 text-3xl font-black {{ $color }}">{{ $value }}</p></article>
        @endforeach
    </section>

    <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[880px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Hora</th><th class="px-5 py-3">Estudiante</th><th class="px-5 py-3">Curso</th><th class="px-5 py-3">Lector</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3 text-right">Observación</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($ultimosRegistros as $registro)<tr class="hover:bg-stone-50/70 dark:hover:bg-slate-800/40"><td class="px-5 py-4 font-mono text-base font-black text-teal-600 dark:text-teal-300">{{ $registro['hora'] }}</td><td class="px-5 py-4"><p class="text-sm font-black">{{ $registro['nombre'] }}</p><p class="mt-0.5 font-mono text-[11px] text-slate-400">{{ $registro['matricula'] }}</p></td><td class="px-5 py-4 text-sm font-semibold text-slate-600 dark:text-slate-300">{{ $registro['curso'] }}</td><td class="px-5 py-4"><p class="text-sm font-bold">{{ $registro['lector'] }}</p>@if ($registro['escuela'])<p class="mt-0.5 text-[11px] text-slate-400">{{ $registro['escuela'] }}</p>@endif</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1.5 text-[11px] font-black {{ $registro['is_late'] ? 'bg-amber-100 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300' : ($registro['tipo'] === 'Entrada' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300' : 'bg-sky-100 text-sky-700 dark:bg-sky-400/10 dark:text-sky-300') }}">{{ $registro['is_late'] ? 'Tardanza' : $registro['tipo'] }}</span></td><td class="px-5 py-4 text-right">@if ($registro['excuse_type'])<span class="text-xs font-black text-sky-600 dark:text-sky-300">Justificada</span><p class="mt-1 text-xs text-slate-500">{{ $registro['excuse_note'] }}</p>@elseif ($registro['is_late'] || $registro['is_early_departure'])<details class="relative inline-block text-left"><summary class="cursor-pointer list-none text-xs font-black text-amber-600">Justificar</summary><form class="absolute right-0 z-20 mt-2 grid w-64 gap-2 rounded-xl border border-stone-200 bg-white p-3 text-left shadow-xl dark:border-slate-700 dark:bg-slate-900" action="{{ route('attendances.excuses.store', $registro['id']) }}" method="POST">@csrf<input type="hidden" name="excuse_type" value="{{ $registro['is_late'] ? 'late' : 'early_departure' }}"><textarea class="rounded-lg border border-stone-200 bg-stone-50 p-2 text-xs dark:border-slate-700 dark:bg-slate-950" name="excuse_note" required placeholder="Motivo de la excusa"></textarea><button class="rounded-lg bg-teal-600 px-3 py-2 text-xs font-black text-white" type="submit">Guardar justificación</button></form></details>@else<span class="text-xs font-bold text-slate-400">Sin alertas</span>@endif</td></tr>@empty<tr><td class="px-6 py-16 text-center text-sm text-slate-500" colspan="6">Esperando el primer registro de hoy.</td></tr>@endforelse</tbody></table></div>
        <div class="divide-y divide-stone-100 md:hidden dark:divide-slate-800">@forelse ($ultimosRegistros as $registro)<div class="grid grid-cols-[auto_1fr_auto] items-center gap-3 px-4 py-4"><time class="font-mono text-sm font-black text-teal-500">{{ substr($registro['hora'], 0, 5) }}</time><div class="min-w-0"><p class="truncate text-sm font-black">{{ $registro['nombre'] }}</p><p class="mt-0.5 truncate text-xs text-slate-500">{{ $registro['curso'] }} · {{ $registro['lector'] }}</p></div><span class="text-[10px] font-black {{ $registro['is_late'] ? 'text-amber-500' : 'text-emerald-500' }}">{{ $registro['is_late'] ? 'TARDANZA' : strtoupper($registro['tipo']) }}</span></div>@empty<p class="px-5 py-14 text-center text-sm text-slate-500">Esperando el primer registro de hoy.</p>@endforelse</div>
    </article>
</section>
