<section id="enrollment" class="scroll-mt-32 space-y-6" data-biometric-enrollment>
    <header class="flex flex-col gap-4 border-b border-stone-200 pb-5 lg:flex-row lg:items-end lg:justify-between dark:border-slate-800">
        <div><p class="text-[11px] font-black uppercase tracking-[.2em] text-teal-500">Estación de enrolamiento</p><h1 class="mt-1 text-2xl font-black tracking-tight">Registro biométrico</h1><p class="mt-1 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-400">Selecciona una persona, elige el tipo de biometría y sigue las instrucciones del lector.</p></div>
        <div class="grid w-full grid-cols-3 overflow-hidden rounded-2xl border border-stone-200 bg-white text-center shadow-sm sm:w-auto dark:border-slate-800 dark:bg-slate-900">
            @foreach ([['Lectores', $enrollmentSummary['active_readers'].' / '.$enrollmentSummary['total_readers']], ['Registros hoy', $enrollmentSummary['today']], ['Pendientes', $enrollmentSummary['pending']]] as [$label, $value])
                <div class="border-l border-stone-200 px-4 py-3 first:border-l-0 dark:border-slate-800"><p class="text-[10px] font-black uppercase tracking-wider text-slate-400">{{ $label }}</p><p class="mt-1 text-lg font-black">{{ $value }}</p></div>
            @endforeach
        </div>
    </header>

    <nav class="relative grid grid-cols-3 rounded-2xl border border-stone-200 bg-white p-2 shadow-sm dark:border-slate-800 dark:bg-slate-900" aria-label="Progreso del registro biométrico">
        <div class="absolute left-[16.66%] right-[16.66%] top-7 h-px bg-stone-200 dark:bg-slate-700"></div>
        @foreach ([['person', '1', 'Persona'], ['biometry', '2', 'Biometría'], ['capture', '3', 'Captura']] as [$step, $number, $label])
            <div class="relative z-10 flex flex-col items-center gap-1.5 rounded-xl px-2 py-2 text-center" data-enrollment-step="{{ $step }}"><span class="flex h-9 w-9 items-center justify-center rounded-full border-2 border-stone-200 bg-white text-xs font-black text-slate-400 transition dark:border-slate-700 dark:bg-slate-900">{{ $number }}</span><span class="text-[10px] font-black uppercase tracking-[.16em] text-slate-400 sm:text-xs">{{ $label }}</span></div>
        @endforeach
    </nav>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
        <div class="space-y-6">
            <article class="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div class="border-b border-stone-100 px-5 py-5 sm:px-7 dark:border-slate-800"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-2xl bg-teal-100 text-sm font-black text-teal-700 dark:bg-teal-400/10 dark:text-teal-300">1</span><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600 dark:text-teal-400">Persona</p><h2 class="mt-0.5 text-lg font-black">Selecciona a quién registrarás</h2></div></div></div>

                <div class="p-5 sm:p-7" data-person-search-panel>
                    <label class="block text-xs font-black uppercase tracking-wider text-slate-500" for="biometric-person-search">Buscar estudiante o persona</label>
                    <div class="relative mt-2"><svg class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m21 21-4.35-4.35M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z"/></svg><input id="biometric-person-search" class="w-full rounded-2xl border border-stone-200 bg-stone-50 py-3.5 pl-12 pr-4 text-sm font-semibold outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-500/10 dark:border-slate-700 dark:bg-slate-950" data-biometric-person-search placeholder="Nombre, matrícula o ID biométrico..." autocomplete="off"></div>
                    <p class="mt-2 text-xs text-slate-400">Escribe al menos dos caracteres para buscar.</p>
                    <div class="mt-4 hidden max-h-80 space-y-2 overflow-y-auto" data-biometric-person-results>
                        @foreach ($students as $student)
                            @php($registeredFingers = $student->enrollments->where('status', 'enrolled')->pluck('finger_index')->unique()->sort()->values()->join(','))
                            <button class="hidden w-full items-center justify-between gap-4 rounded-2xl border border-stone-200 p-4 text-left transition hover:border-teal-400 hover:bg-teal-50/60 dark:border-slate-700 dark:hover:border-teal-700 dark:hover:bg-teal-950/30" type="button" data-biometric-person-option data-student-id="{{ $student->id }}" data-student-name="{{ $student->nombre }} {{ $student->apellido }}" data-student-matricula="{{ $student->matricula }}" data-student-course="{{ $student->curso }}" data-student-biometric-id="{{ $student->id_lector }}" data-student-school="{{ $student->school_id }}" data-student-fingers="{{ $registeredFingers }}" data-student-face-status="{{ $student->face_sync_status }}" data-student-search="{{ Str::lower($student->nombre.' '.$student->apellido.' '.$student->matricula.' '.$student->id_lector.' '.$student->curso) }}">
                                <span class="min-w-0"><strong class="block truncate text-sm">{{ $student->nombre }} {{ $student->apellido }}</strong><span class="mt-1 block truncate text-xs text-slate-500">{{ $student->matricula }} · {{ $student->curso }} · ID {{ $student->id_lector ?: 'sin asignar' }}</span></span><span class="shrink-0 text-teal-600">→</span>
                            </button>
                        @endforeach
                        <p class="hidden rounded-2xl border border-dashed border-stone-200 p-6 text-center text-sm text-slate-500 dark:border-slate-700" data-biometric-person-empty>No se encontraron personas.</p>
                    </div>
                </div>

                <div class="hidden p-5 sm:p-7" data-selected-person-panel>
                    <div class="flex flex-col gap-5 rounded-2xl bg-teal-950 p-5 text-white sm:flex-row sm:items-center sm:justify-between"><div class="flex min-w-0 items-center gap-4"><span class="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-amber-300 text-lg font-black text-teal-950" data-selected-person-initials>--</span><div class="min-w-0"><p class="text-[10px] font-black uppercase tracking-[.18em] text-teal-300">Persona seleccionada</p><h3 class="mt-1 truncate text-xl font-black" data-selected-person-name></h3><p class="mt-1 text-sm text-teal-100/70"><span data-selected-person-matricula></span> · <span data-selected-person-course></span></p><p class="mt-1 font-mono text-xs text-teal-200">ID biométrico: <span data-selected-person-id></span></p></div></div><button class="rounded-xl border border-white/15 px-4 py-2.5 text-xs font-black text-white hover:bg-white/10" type="button" data-change-biometric-person>Cambiar persona</button></div>
                    <div class="mt-5 grid gap-4 sm:grid-cols-2"><div class="rounded-2xl border border-stone-200 p-4 dark:border-slate-700"><p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Huellas registradas</p><div class="mt-3 flex flex-wrap gap-2" data-selected-person-fingers></div></div><div class="rounded-2xl border border-stone-200 p-4 dark:border-slate-700"><p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Reconocimiento facial</p><p class="mt-3 text-sm font-black" data-selected-person-face></p></div></div>
                </div>
            </article>

            <article class="hidden overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" data-biometry-choice-panel>
                <div class="border-b border-stone-100 px-5 py-5 sm:px-7 dark:border-slate-800"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-2xl bg-teal-100 text-sm font-black text-teal-700 dark:bg-teal-400/10 dark:text-teal-300">2</span><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600 dark:text-teal-400">Biometría</p><h2 class="mt-0.5 text-lg font-black">¿Qué deseas registrar?</h2></div></div></div>
                <div class="grid gap-4 p-5 sm:grid-cols-2 sm:p-7">
                    <button class="group rounded-2xl border-2 border-stone-200 p-5 text-left transition hover:border-teal-500 hover:bg-teal-50/50 dark:border-slate-700 dark:hover:border-teal-600 dark:hover:bg-teal-950/20" type="button" data-biometric-choice="fingerprint"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-100 text-2xl dark:bg-teal-400/10">☝</span><strong class="mt-5 block text-base font-black">Huella digital</strong><span class="mt-2 block text-sm leading-6 text-slate-500">Registra un dedo en uno de los lectores biométricos disponibles.</span><span class="mt-5 inline-flex text-xs font-black text-teal-700 dark:text-teal-300">Registrar huella →</span></button>
                    <button class="group rounded-2xl border-2 border-stone-200 p-5 text-left transition hover:border-amber-400 hover:bg-amber-50/60 dark:border-slate-700 dark:hover:border-amber-500 dark:hover:bg-amber-950/15" type="button" data-biometric-choice="face"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-100 text-2xl dark:bg-amber-400/10">◎</span><strong class="mt-5 block text-base font-black">Reconocimiento facial</strong><span class="mt-2 block text-sm leading-6 text-slate-500">Guarda una fotografía JPG y sincronízala con un lector ADMS.</span><span class="mt-5 inline-flex text-xs font-black text-amber-700 dark:text-amber-300">Registrar rostro →</span></button>
                </div>
            </article>

            <article class="hidden overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" data-capture-panel>
                <div class="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-5 sm:px-7 dark:border-slate-800"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-2xl bg-amber-100 text-sm font-black text-amber-700 dark:bg-amber-400/10 dark:text-amber-300">3</span><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-amber-600 dark:text-amber-400">Captura</p><h2 class="mt-0.5 text-lg font-black" data-capture-title></h2></div></div><button class="text-xs font-black text-teal-700 dark:text-teal-300" type="button" data-change-biometric-type>Cambiar biometría</button></div>

                <form class="hidden space-y-5 p-5 sm:p-7" action="{{ route('devices.enroll') }}" method="POST" data-fingerprint-enrollment-form>
                    @csrf
                    <select class="sr-only" name="student_id" required data-biometric-student-select><option value="">Seleccionar estudiante</option>@foreach ($students as $student)<option value="{{ $student->id }}">{{ $student->nombre }} {{ $student->apellido }}</option>@endforeach</select>
                    <div class="rounded-2xl bg-stone-50 p-4 dark:bg-slate-950"><p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Persona</p><p class="mt-1 font-black" data-form-person-name></p></div>
                    <label class="block text-xs font-black uppercase tracking-wider text-slate-500">Lector<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="biometric_device_id" required><option value="">Seleccionar lector</option>@foreach ($devices->where('is_active', true) as $device)@php([$deviceLabel, $deviceClass] = $statusMeta[$device->connectionStatus()])<option value="{{ $device->id }}">{{ $device->name }} · {{ $deviceLabel }}</option>@endforeach</select></label>
                    <label class="block text-xs font-black uppercase tracking-wider text-slate-500">Dedo<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="finger_index" required data-finger-index>@foreach ($fingerNames as $index => $finger)<option value="{{ $index }}">{{ $finger }}</option>@endforeach</select></label>
                    <div class="rounded-2xl border border-teal-200 bg-teal-50/60 p-5 dark:border-teal-900 dark:bg-teal-950/30"><p class="text-[10px] font-black uppercase tracking-wider text-teal-700 dark:text-teal-300">Proceso de captura</p><p class="mt-2 text-sm font-black">El lector solicitará tres muestras reales del dedo.</p><p class="mt-1 text-xs leading-5 text-slate-500">El progreso aparecerá en Actividad reciente conforme el SDK o ADMS actualice la operación.</p><div class="mt-4 flex gap-2"><span class="h-2.5 w-2.5 rounded-full bg-stone-300 dark:bg-slate-700"></span><span class="h-2.5 w-2.5 rounded-full bg-stone-300 dark:bg-slate-700"></span><span class="h-2.5 w-2.5 rounded-full bg-stone-300 dark:bg-slate-700"></span></div></div>
                    <button class="flex w-full items-center justify-center gap-2 rounded-xl bg-amber-300 px-4 py-3.5 text-sm font-black text-teal-950 shadow-lg shadow-amber-900/10 hover:bg-amber-200" type="submit">Iniciar registro en el lector</button>
                </form>

                <form class="hidden space-y-5 p-5 sm:p-7" action="{{ route('devices.enroll-face') }}" method="POST" enctype="multipart/form-data" data-face-enrollment-form>
                    @csrf
                    <select class="sr-only" name="student_id" required data-biometric-student-select><option value="">Seleccionar estudiante</option>@foreach ($students as $student)<option value="{{ $student->id }}">{{ $student->nombre }} {{ $student->apellido }}</option>@endforeach</select>
                    <div class="rounded-2xl bg-stone-50 p-4 dark:bg-slate-950"><p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Persona</p><p class="mt-1 font-black" data-form-person-name></p></div>
                    <label class="block text-xs font-black uppercase tracking-wider text-slate-500">Lector<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="biometric_device_id" required><option value="">Seleccionar lector ADMS</option>@foreach ($devices->where('is_active', true)->whereIn('connection_mode', ['adms', 'hybrid']) as $device)<option value="{{ $device->id }}">{{ $device->name }} · {{ $statusMeta[$device->connectionStatus()][0] }}</option>@endforeach</select></label>
                    <label class="block text-xs font-black uppercase tracking-wider text-slate-500">Fotografía JPG<input class="mt-2 block w-full rounded-xl border border-stone-200 bg-stone-50 px-3 py-3 text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-teal-700 file:px-3 file:py-2 file:font-bold file:text-white dark:border-slate-700 dark:bg-slate-950" type="file" name="face_photo" accept="image/jpeg" capture="user" required data-face-photo></label>
                    <div class="hidden overflow-hidden rounded-2xl border border-stone-200 bg-stone-50 p-3 dark:border-slate-700 dark:bg-slate-950" data-face-preview-panel><img class="mx-auto max-h-64 rounded-xl object-contain" alt="Vista previa de la fotografía seleccionada" data-face-preview></div>
                    <label class="flex items-start gap-3 rounded-2xl border border-stone-200 p-4 text-xs leading-5 text-slate-600 dark:border-slate-700 dark:text-slate-300"><input class="mt-1 h-4 w-4 accent-teal-600" type="checkbox" name="biometric_consent" value="1" required><span>Confirmo que tengo autorización para registrar y procesar esta fotografía biométrica.</span></label>
                    <button class="flex w-full items-center justify-center rounded-xl bg-amber-300 px-4 py-3.5 text-sm font-black text-teal-950 shadow-lg shadow-amber-900/10 hover:bg-amber-200" type="submit">Guardar y sincronizar rostro</button>
                </form>
            </article>
        </div>

        <aside class="self-start overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm xl:sticky xl:top-28 dark:border-slate-800 dark:bg-slate-900">
            <header class="border-b border-stone-100 px-5 py-5 dark:border-slate-800"><p class="text-[11px] font-black uppercase tracking-[.18em] text-sky-600 dark:text-sky-400">Seguimiento real</p><h2 class="mt-1 text-lg font-black">Actividad reciente</h2></header>
            <div class="max-h-[42rem] divide-y divide-stone-100 overflow-y-auto dark:divide-slate-800">
                @forelse ($enrollments as $enrollment)
                    @php([$activityLabel, $activityClass] = match ($enrollment->status) { 'enrolled' => ['Huella registrada', 'bg-emerald-500'], 'failed' => ['Registro fallido', 'bg-rose-500'], 'processing' => ['Captura en proceso', 'bg-amber-500'], default => ['Registro enviado', 'bg-sky-500'] })
                    <div class="flex gap-3 px-5 py-4"><span class="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full {{ $activityClass }}"></span><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-black">{{ $activityLabel }}</p><p class="mt-1 truncate text-xs font-bold text-slate-600 dark:text-slate-300">{{ $enrollment->student?->nombre }} {{ $enrollment->student?->apellido }}</p></div><time class="shrink-0 font-mono text-[10px] text-slate-400">{{ $enrollment->updated_at->format('H:i') }}</time></div><p class="mt-1 text-xs text-slate-500">{{ $fingerNames[$enrollment->finger_index] ?? 'Dedo '.$enrollment->finger_index }} · {{ $enrollment->device?->name }}</p>@if ($enrollment->error)<p class="mt-2 rounded-lg bg-rose-50 px-2 py-1.5 text-[11px] text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{{ $enrollment->error }}</p>@endif @if ($enrollment->status === 'failed')<form class="mt-2" action="{{ route('devices.enrollments.verify', $enrollment) }}" method="POST">@csrf<button class="text-[11px] font-black text-teal-700 underline decoration-teal-300 underline-offset-4 dark:text-teal-300" type="submit">Verificar plantilla</button></form>@endif</div></div>
                @empty
                    <div class="px-5 py-12 text-center"><span class="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-stone-100 text-xl dark:bg-slate-800">◌</span><p class="mt-3 text-sm font-black">Aún no hay operaciones recientes</p><p class="mt-1 text-xs leading-5 text-slate-500">Los registros enviados al lector aparecerán aquí.</p></div>
                @endforelse
            </div>
        </aside>
    </div>
</section>
