<section class="space-y-6" data-reports-dashboard>
    <header class="flex flex-col gap-4 border-b border-stone-200 pb-5 lg:flex-row lg:items-end lg:justify-between dark:border-slate-800">
        <div><p class="text-[11px] font-black uppercase tracking-[.2em] text-violet-500">Análisis histórico</p><h1 class="mt-1 text-2xl font-black tracking-tight">Reportes de asistencia</h1><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Consulta el comportamiento de asistencia, puntualidad e incidencias por período y curso.</p></div>
        <span class="w-fit rounded-full bg-violet-100 px-3 py-2 text-xs font-black text-violet-700 dark:bg-violet-400/10 dark:text-violet-300">{{ $reportStartDate->format('d/m/Y') }} — {{ $reportEndDate->format('d/m/Y') }}</span>
    </header>

    <form class="grid gap-4 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1.1fr_1.4fr_auto] xl:items-end dark:border-slate-800 dark:bg-slate-900" method="GET" action="{{ route($dashboardPageRoute, 'reports') }}" data-report-filter-form>
        @if ($selectedSchoolId && ($usuario['role'] ?? null) === 'superadmin')<input type="hidden" name="school_id" value="{{ $selectedSchoolId }}">@endif
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Desde<input class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" type="date" name="report_start" value="{{ $reportStartDate->format('Y-m-d') }}"></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Hasta<input class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" type="date" name="report_end" value="{{ $reportEndDate->format('Y-m-d') }}"></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Curso<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="course"><option value="">Todos los cursos</option>@foreach ($reportCourses as $course)<option value="{{ $course }}" @selected($selectedCourse === $course)>{{ $course }}</option>@endforeach</select></label>
        <div class="relative" data-report-student-search><label class="text-xs font-black uppercase tracking-wider text-slate-500" for="report-student-search">Estudiante</label><input type="hidden" name="report_student_id" value="{{ $selectedReportStudent?->id }}" data-report-student-id><input id="report-student-search" class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" type="search" value="{{ $selectedReportStudent ? $selectedReportStudent->nombre.' '.$selectedReportStudent->apellido : '' }}" placeholder="Buscar por nombre..." autocomplete="off" data-report-student-input><div class="absolute left-0 right-0 z-30 mt-2 hidden max-h-72 overflow-y-auto rounded-2xl border border-stone-200 bg-white p-2 shadow-2xl dark:border-slate-700 dark:bg-slate-900" data-report-student-results>@foreach ($reportStudents as $student)<button class="hidden w-full rounded-xl px-3 py-3 text-left hover:bg-teal-50 dark:hover:bg-teal-950/30" type="button" data-report-student-option data-student-id="{{ $student->id }}" data-student-name="{{ $student->nombre }} {{ $student->apellido }}" data-student-search="{{ Str::lower($student->nombre.' '.$student->apellido) }}"><strong class="block text-sm">{{ $student->nombre }} {{ $student->apellido }}</strong><span class="mt-1 block text-xs text-slate-500">{{ $student->matricula }} · {{ $student->curso }}</span></button>@endforeach<p class="hidden p-4 text-center text-xs text-slate-500" data-report-student-empty>No se encontraron estudiantes.</p></div>@if ($selectedReportStudent)<button class="absolute right-3 top-[2.15rem] rounded-lg px-2 py-1 text-xs font-black text-slate-400 hover:text-rose-500" type="button" aria-label="Quitar estudiante" data-clear-report-student>×</button>@endif</div>
        <button class="rounded-xl bg-violet-600 px-5 py-3 text-sm font-black text-white hover:bg-violet-500" type="submit">Generar reporte</button>
    </form>

    @if ($selectedReportStudent)
        <article class="overflow-hidden rounded-2xl border border-violet-200 bg-gradient-to-br from-violet-50 to-white shadow-sm dark:border-violet-900 dark:from-violet-950/40 dark:to-slate-900" data-individual-student-report>
            <div class="grid gap-5 p-5 lg:grid-cols-[minmax(0,1.4fr)_repeat(3,minmax(0,.7fr))] lg:items-center"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-violet-600 dark:text-violet-300">Reporte individual de asistencia</p><h2 class="mt-2 text-2xl font-black">{{ $selectedReportStudent->nombre }} {{ $selectedReportStudent->apellido }}</h2><p class="mt-1 text-sm text-slate-500">{{ $selectedReportStudent->matricula }} · {{ $selectedReportStudent->curso }}</p></div>@foreach ([['Días con asistencia', $reportStudentSummary['attendance_days'], 'text-emerald-600'], ['Tardanzas', $reportStudentSummary['late_days'], 'text-amber-600'], ['Días sin entrada', $reportStudentSummary['days_without_entry'], 'text-rose-600']] as [$label, $value, $color])<div class="rounded-2xl border border-white/70 bg-white/80 p-4 dark:border-slate-700 dark:bg-slate-900/70"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black {{ $color }}">{{ $value }}</p></div>@endforeach</div>
            <p class="border-t border-violet-100 px-5 py-3 text-[11px] text-slate-500 dark:border-violet-900">“Días sin entrada” cuenta los días de lunes a viernes del período sin un registro de entrada. Feriados o días no lectivos deben verificarse con el calendario escolar.</p>
        </article>
    @endif

    <section class="grid grid-cols-2 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm lg:grid-cols-4 dark:border-slate-800 dark:bg-slate-900">
        @foreach ([['Estudiantes activos', $reportSummary['students'], 'text-sky-500'], ['Asistencias', $reportSummary['entries'], 'text-emerald-500'], ['Tardanzas', $reportSummary['late'], 'text-amber-500'], ['Justificaciones', $reportSummary['excused'], 'text-violet-500']] as [$label, $value, $color])
            <article class="border-stone-200 px-5 py-5 even:border-l lg:border-l lg:first:border-l-0 dark:border-slate-800"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black {{ $color }}">{{ number_format($value) }}</p></article>
        @endforeach
    </section>

    <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" data-gender-report>
        <header class="flex flex-col gap-2 border-b border-stone-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-fuchsia-600 dark:text-fuchsia-400">Matrícula oficial</p><h2 class="mt-1 text-lg font-black">Femenino y masculino por curso</h2><p class="mt-1 text-xs text-slate-500">Los estudiantes sin el dato registrado se mantienen separados para no alterar los totales.</p></div><span class="w-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black text-slate-700 dark:bg-slate-800 dark:text-slate-200">Total general: {{ number_format($reportGenderTotals['total']) }}</span></header>
        <div class="overflow-x-auto"><table class="w-full min-w-[640px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Curso</th><th class="px-5 py-3 text-center">Femenino</th><th class="px-5 py-3 text-center">Masculino</th><th class="px-5 py-3 text-center">Sin especificar</th><th class="px-5 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($reportGenderByCourse as $course)<tr><td class="px-5 py-4 font-black">{{ $course['course'] }}</td><td class="px-5 py-4 text-center text-lg font-black text-fuchsia-600 dark:text-fuchsia-300">{{ $course['female'] }}</td><td class="px-5 py-4 text-center text-lg font-black text-sky-600 dark:text-sky-300">{{ $course['male'] }}</td><td class="px-5 py-4 text-center text-sm font-bold text-slate-400">{{ $course['unspecified'] }}</td><td class="px-5 py-4 text-right text-lg font-black">{{ $course['total'] }}</td></tr>@empty<tr><td class="px-5 py-12 text-center text-sm text-slate-500" colspan="5">No hay estudiantes para los filtros seleccionados.</td></tr>@endforelse</tbody>@if ($reportGenderByCourse->isNotEmpty())<tfoot class="border-t-2 border-stone-200 bg-stone-50 font-black dark:border-slate-700 dark:bg-slate-950"><tr><td class="px-5 py-4">Total general</td><td class="px-5 py-4 text-center text-fuchsia-600 dark:text-fuchsia-300">{{ $reportGenderTotals['female'] }}</td><td class="px-5 py-4 text-center text-sky-600 dark:text-sky-300">{{ $reportGenderTotals['male'] }}</td><td class="px-5 py-4 text-center text-slate-400">{{ $reportGenderTotals['unspecified'] }}</td><td class="px-5 py-4 text-right text-xl">{{ $reportGenderTotals['total'] }}</td></tr></tfoot>@endif</table></div>
    </article>

    <section class="grid gap-5 xl:grid-cols-5">
        <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm xl:col-span-3 dark:border-slate-800 dark:bg-slate-900">
            <header class="border-b border-stone-100 px-5 py-4 dark:border-slate-800"><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600 dark:text-teal-400">Comparación</p><h2 class="mt-1 text-lg font-black">Rendimiento por curso</h2></header>
            <div class="overflow-x-auto"><table class="w-full min-w-[620px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Curso</th><th class="px-5 py-3">Estudiantes</th><th class="px-5 py-3">Asistencias</th><th class="px-5 py-3">Tardanzas</th><th class="px-5 py-3 text-right">Puntualidad</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($reportByCourse as $course)<tr><td class="px-5 py-4 font-black">{{ $course['course'] }}</td><td class="px-5 py-4 text-sm text-slate-500">{{ $course['students'] }}</td><td class="px-5 py-4 text-sm font-bold text-emerald-600">{{ $course['entries'] }}</td><td class="px-5 py-4 text-sm font-bold text-amber-600">{{ $course['late'] }}</td><td class="px-5 py-4 text-right"><span class="rounded-full bg-teal-50 px-3 py-1.5 text-xs font-black text-teal-700 dark:bg-teal-400/10 dark:text-teal-300">{{ $course['on_time_percentage'] }}%</span></td></tr>@empty<tr><td class="px-5 py-12 text-center text-sm text-slate-500" colspan="5">No hay datos para el período seleccionado.</td></tr>@endforelse</tbody></table></div>
        </article>

        <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm xl:col-span-2 dark:border-slate-800 dark:bg-slate-900">
            <header class="border-b border-stone-100 px-5 py-4 dark:border-slate-800"><p class="text-[11px] font-black uppercase tracking-[.18em] text-sky-600 dark:text-sky-400">Tendencia</p><h2 class="mt-1 text-lg font-black">Actividad por día</h2></header>
            <div class="max-h-96 divide-y divide-stone-100 overflow-y-auto dark:divide-slate-800">@forelse ($reportByDay as $day)<div class="flex items-center justify-between gap-4 px-5 py-4"><div><p class="text-sm font-black">{{ $day['date']->locale('es')->isoFormat('dddd D [de] MMMM') }}</p><p class="mt-1 text-xs text-slate-500">{{ $day['late'] }} tardanza{{ $day['late'] === 1 ? '' : 's' }}</p></div><span class="text-2xl font-black text-sky-500">{{ $day['entries'] }}</span></div>@empty<p class="px-5 py-12 text-center text-sm text-slate-500">Sin actividad en este período.</p>@endforelse</div>
        </article>
    </section>

    <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <header class="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-4 dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-violet-600 dark:text-violet-400">Detalle auditable</p><h2 class="mt-1 text-lg font-black">Registros del período</h2></div><span class="rounded-full bg-stone-100 px-3 py-1.5 text-xs font-black text-slate-600 dark:bg-slate-800 dark:text-slate-300">Últimos {{ $reportRecords->count() }} registros</span></header>
        <div class="overflow-x-auto"><table class="w-full min-w-[820px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Fecha y hora</th><th class="px-5 py-3">Estudiante</th><th class="px-5 py-3">Curso</th><th class="px-5 py-3">Movimiento</th><th class="px-5 py-3 text-right">Condición</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($reportRecords as $record)<tr><td class="px-5 py-4 font-mono text-xs font-bold text-slate-500">{{ $record->fecha_hora->format('d/m/Y H:i') }}</td><td class="px-5 py-4"><p class="text-sm font-black">{{ $record->student?->nombre }} {{ $record->student?->apellido }}</p><p class="mt-1 font-mono text-[11px] text-slate-400">{{ $record->matricula }}</p></td><td class="px-5 py-4 text-sm font-semibold">{{ $record->curso }}</td><td class="px-5 py-4"><span class="rounded-full bg-sky-50 px-3 py-1.5 text-xs font-black text-sky-700 dark:bg-sky-400/10 dark:text-sky-300">{{ $record->tipo }}</span></td><td class="px-5 py-4 text-right"><span class="text-xs font-black {{ $record->is_late ? 'text-amber-600' : 'text-emerald-600' }}">{{ $record->is_late ? 'Tardanza' : 'A tiempo' }}</span>@if ($record->excuse_type)<p class="mt-1 text-[11px] text-violet-500">Justificada</p>@endif</td></tr>@empty<tr><td class="px-5 py-14 text-center text-sm text-slate-500" colspan="5">No se encontraron registros para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>
    </article>
</section>
