<section class="space-y-6" data-reports-dashboard>
    <header class="flex flex-col gap-4 border-b border-stone-200 pb-5 lg:flex-row lg:items-end lg:justify-between dark:border-slate-800">
        <div><p class="text-[11px] font-black uppercase tracking-[.2em] text-violet-500">Análisis histórico</p><h1 class="mt-1 text-2xl font-black tracking-tight">Reportes de asistencia</h1><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Consulta el comportamiento de asistencia, puntualidad e incidencias por período y curso.</p></div>
        <span class="w-fit rounded-full bg-violet-100 px-3 py-2 text-xs font-black text-violet-700 dark:bg-violet-400/10 dark:text-violet-300">{{ $reportStartDate->format('d/m/Y') }} — {{ $reportEndDate->format('d/m/Y') }}</span>
    </header>

    <form class="grid gap-4 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:grid-cols-2 xl:grid-cols-4 dark:border-slate-800 dark:bg-slate-900" method="GET" action="{{ route($dashboardPageRoute, 'reports') }}" data-report-filter-form data-report-presets>
        @if ($selectedSchoolId && ($usuario['role'] ?? null) === 'superadmin')<input type="hidden" name="school_id" value="{{ $selectedSchoolId }}">@endif
        <input type="hidden" name="show_report" value="1">
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Tipo de reporte<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="report_type"><option value="general" @selected($reportType === 'general')>Resumen general</option><option value="course" @selected($reportType === 'course')>Por curso</option><option value="student" @selected($reportType === 'student')>Estudiante individual</option><option value="history" @selected($reportType === 'history')>Historial detallado</option></select></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Desde<input class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" type="date" name="report_start" value="{{ $reportStartDate->format('Y-m-d') }}"></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Hasta<input class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" type="date" name="report_end" value="{{ $reportEndDate->format('Y-m-d') }}"></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Curso<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="course"><option value="">Todos los cursos</option>@foreach ($reportCourses as $course)<option value="{{ $course }}" @selected($selectedCourse === $course)>{{ $course }}</option>@endforeach</select></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Área<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="report_area"><option value="">Todas las áreas</option>@foreach($reportAreas as $area)<option value="{{ $area }}" @selected($reportArea === $area)>{{ $area }}</option>@endforeach</select></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Estado<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="report_status"><option value="all" @selected($reportStatus === 'all')>Todos P/T/E/A</option><option value="present" @selected($reportStatus === 'present')>Presentes</option><option value="late" @selected($reportStatus === 'late')>Tardanzas</option><option value="excused" @selected($reportStatus === 'excused')>Excusas</option><option value="absent" @selected($reportStatus === 'absent')>Ausencias</option></select></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Sexo<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" name="report_sex"><option value="all" @selected($reportSex === 'all')>Todos</option><option value="Femenino" @selected($reportSex === 'Femenino')>Femenino</option><option value="Masculino" @selected($reportSex === 'Masculino')>Masculino</option><option value="Sin especificar" @selected($reportSex === 'Sin especificar')>Sin especificar</option></select></label>
        <label class="text-xs font-black uppercase tracking-wider text-slate-500">Riesgo por debajo de<input class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" type="number" min="1" max="100" name="report_risk_threshold" value="{{ $reportRiskThreshold }}"></label>
        <div class="relative" data-report-student-search><label class="text-xs font-black uppercase tracking-wider text-slate-500" for="report-student-search">Estudiante</label><input type="hidden" name="report_student_id" value="{{ $selectedReportStudent?->id }}" data-report-student-id><input id="report-student-search" class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-4 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-950" type="search" value="{{ $selectedReportStudent ? $selectedReportStudent->nombre.' '.$selectedReportStudent->apellido : '' }}" placeholder="Buscar por nombre..." autocomplete="off" data-report-student-input><div class="absolute left-0 right-0 z-30 mt-2 hidden max-h-72 overflow-y-auto rounded-2xl border border-stone-200 bg-white p-2 shadow-2xl dark:border-slate-700 dark:bg-slate-900" data-report-student-results>@foreach ($reportStudents as $student)<button class="hidden w-full rounded-xl px-3 py-3 text-left hover:bg-teal-50 dark:hover:bg-teal-950/30" type="button" data-report-student-option data-student-id="{{ $student->id }}" data-student-name="{{ $student->nombre }} {{ $student->apellido }}" data-student-search="{{ Str::lower($student->nombre.' '.$student->apellido) }}"><strong class="block text-sm">{{ $student->nombre }} {{ $student->apellido }}</strong><span class="mt-1 block text-xs text-slate-500">{{ $student->matricula }} · {{ $student->curso }}</span></button>@endforeach<p class="hidden p-4 text-center text-xs text-slate-500" data-report-student-empty>No se encontraron estudiantes.</p></div>@if ($selectedReportStudent)<button class="absolute right-3 top-[2.15rem] rounded-lg px-2 py-1 text-xs font-black text-slate-400 hover:text-rose-500" type="button" aria-label="Quitar estudiante" data-clear-report-student>×</button>@endif</div>
        <div class="flex items-end gap-2 xl:col-span-3"><button class="flex-1 rounded-xl bg-violet-600 px-5 py-3 text-sm font-black text-white hover:bg-violet-500" type="submit">Generar reporte</button><button class="rounded-xl border border-violet-200 px-4 py-3 text-sm font-black text-violet-700 dark:border-violet-800 dark:text-violet-300" type="button" data-save-report-preset>Guardar filtros</button><button class="rounded-xl border border-stone-200 px-4 py-3 text-sm font-black text-slate-600 dark:border-slate-700 dark:text-slate-300" type="button" data-load-report-preset>Aplicar guardados</button></div>
    </form>

    <dialog id="generated-report-dialog" class="m-auto max-h-[95vh] w-[min(1500px,98vw)] overflow-hidden rounded-3xl border-0 bg-stone-50 p-0 text-slate-900 shadow-2xl backdrop:bg-slate-950/80 dark:bg-slate-950 dark:text-slate-100" data-generated-report-dialog @if(request()->boolean('show_report')) data-report-autopen @endif>
        <header class="flex items-start justify-between gap-4 bg-slate-950 px-6 py-5 text-white"><div><p class="text-[11px] font-black uppercase tracking-[.2em] text-violet-400">{{ $reportNumber }}</p><h2 class="mt-1 text-2xl font-black">Reporte de asistencia · {{ ['general'=>'General','course'=>'Por curso','student'=>'Individual','history'=>'Historial'][$reportType] }}</h2><p class="mt-1 text-sm text-slate-400">{{ $reportStartDate->format('d/m/Y') }} — {{ $reportEndDate->format('d/m/Y') }} @if($selectedCourse)· {{ $selectedCourse }}@endif @if($reportArea)· {{ $reportArea }}@endif</p></div><div class="flex gap-2"><button class="rounded-xl bg-white/10 px-4 py-2 text-xs font-black" type="button" data-print-report>Imprimir / PDF</button><a class="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black" href="{{ route('reports.export', request()->query()) }}">Excel</a><button class="rounded-full bg-white/10 px-3 py-2 text-xl" type="button" data-close-dialog>×</button></div></header>
        <div class="max-h-[calc(95vh-5rem)] space-y-6 overflow-y-auto p-5 sm:p-6" data-printable-report>

    <section class="grid grid-cols-2 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm lg:grid-cols-6 dark:border-slate-800 dark:bg-slate-900">
        @foreach ([['Clases impartidas', $reportClassSummary['sessions'], 'text-violet-500'], ['Presentes', $reportClassSummary['present'], 'text-emerald-500'], ['Tardanzas', $reportClassSummary['late'], 'text-amber-500'], ['Excusas', $reportClassSummary['excused'], 'text-sky-500'], ['Ausencias', $reportClassSummary['absent'], 'text-rose-500'], ['En riesgo', $reportRiskStudents->count(), 'text-orange-500']] as [$label, $value, $color])
            <article class="border-stone-200 px-4 py-5 even:border-l lg:border-l lg:first:border-l-0 dark:border-slate-800"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black {{ $color }}">{{ number_format($value) }}</p></article>
        @endforeach
    </section>

    @if($reportIncompleteSessions->isNotEmpty())<aside class="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><strong>{{ $reportIncompleteSessions->count() }} clase(s) todavía están abiertas.</strong> Deben cerrarse para consolidar el período.</aside>@endif

    <section class="grid gap-5 lg:grid-cols-3">
        <article class="rounded-2xl border border-stone-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-black uppercase text-slate-500">Comparación anterior</p><p class="mt-3 text-3xl font-black">{{ $reportPreviousSummary['attendance_percentage'] }}%</p><p class="mt-1 text-xs text-slate-500">{{ $reportPreviousSummary['sessions'] }} clases en el período anterior equivalente.</p></article>
        <article class="rounded-2xl border border-stone-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-black uppercase text-slate-500">Regla aplicada</p><p class="mt-3 text-sm font-bold">3 tardanzas = 1 inasistencia<br>3 excusas = 1 inasistencia</p></article>
        <article class="rounded-2xl border border-stone-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-black uppercase text-slate-500">Umbral de seguimiento</p><p class="mt-3 text-3xl font-black text-orange-500">{{ $reportRiskThreshold }}%</p><p class="mt-1 text-xs text-slate-500">Se señalan resultados por debajo de este valor.</p></article>
    </section>

    @if(in_array($reportType, ['general', 'course'], true))
        <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" data-class-course-report>
            <header class="border-b border-stone-100 px-5 py-4 dark:border-slate-800"><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600">Registro docente</p><h3 class="mt-1 text-lg font-black">Asistencia individual por curso</h3></header>
            <div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left"><thead class="bg-stone-50 text-[10px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-4 py-3">Curso</th><th class="px-4 py-3 text-center">Clases</th><th class="px-4 py-3 text-center">Estudiantes</th><th class="px-4 py-3 text-center">Presentes</th><th class="px-4 py-3 text-center">Tardanzas</th><th class="px-4 py-3 text-center">Ausencias</th><th class="px-4 py-3 text-right">Asistencia</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse($reportClassCourses as $row)<tr><td class="px-4 py-4"><p class="font-black">{{ $row['course']->name }}</p><p class="text-xs text-slate-500">{{ $row['course']->grade }} {{ $row['course']->section }} · {{ $row['course']->area ?: 'Sin área' }}</p></td><td class="px-4 py-4 text-center font-black">{{ $row['sessions'] }}</td><td class="px-4 py-4 text-center">{{ $row['students'] }}</td><td class="px-4 py-4 text-center font-black text-emerald-600">{{ $row['present'] }}</td><td class="px-4 py-4 text-center font-black text-amber-600">{{ $row['late'] }}</td><td class="px-4 py-4 text-center font-black text-rose-600">{{ $row['absent'] }}</td><td class="px-4 py-4 text-right"><span class="rounded-full bg-teal-50 px-3 py-1.5 text-xs font-black text-teal-700">{{ $row['percentage'] }}%</span></td></tr>@empty<tr><td class="px-5 py-12 text-center text-sm text-slate-500" colspan="7">No hay clases registradas para estos filtros.</td></tr>@endforelse</tbody></table></div>
        </article>
    @endif

    @if(in_array($reportType, ['general', 'course', 'student'], true))
        <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" data-student-class-report>
            <header class="flex flex-col gap-2 border-b border-stone-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-violet-600">Detalle por estudiante</p><h3 class="mt-1 text-lg font-black">P, T, E, A y porcentaje válido</h3></div><span class="text-xs text-slate-500">{{ $reportStudentRows->count() }} estudiante(s)</span></header>
            <div class="max-h-[30rem] overflow-auto"><table class="w-full min-w-[950px] text-left"><thead class="sticky top-0 bg-stone-50 text-[10px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-4 py-3">Estudiante</th><th class="px-4 py-3">Curso</th><th class="px-4 py-3 text-center">Clases</th><th class="px-4 py-3 text-center">P</th><th class="px-4 py-3 text-center">T</th><th class="px-4 py-3 text-center">E</th><th class="px-4 py-3 text-center">A</th><th class="px-4 py-3 text-center">IE</th><th class="px-4 py-3 text-center">AV</th><th class="px-4 py-3 text-right">%</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse($reportStudentRows as $row)<tr class="{{ $row['sessionCount'] > 0 && $row['percentage'] < $reportRiskThreshold ? 'bg-orange-50/70 dark:bg-orange-950/20' : '' }}"><td class="px-4 py-3"><p class="font-black">{{ $row['student']->apellido }}, {{ $row['student']->nombre }}</p><p class="text-[10px] text-slate-500">{{ $row['student']->matricula }} · {{ $row['student']->sexo ?: 'Sin especificar' }}</p></td><td class="px-4 py-3 text-xs font-bold">{{ $row['student']->curso }}</td><td class="px-4 py-3 text-center">{{ $row['sessionCount'] }}</td><td class="px-4 py-3 text-center font-black text-emerald-600">{{ $row['present'] }}</td><td class="px-4 py-3 text-center font-black text-amber-600">{{ $row['late'] }}</td><td class="px-4 py-3 text-center font-black text-sky-600">{{ $row['excused'] }}</td><td class="px-4 py-3 text-center font-black text-rose-600">{{ $row['absent'] }}</td><td class="px-4 py-3 text-center font-black">{{ $row['equivalentAbsences'] }}</td><td class="px-4 py-3 text-center font-black text-violet-600">{{ $row['credited'] }}/{{ $row['sessionCount'] }}</td><td class="px-4 py-3 text-right"><span class="rounded-full px-3 py-1 text-xs font-black {{ $row['percentage'] >= $reportRiskThreshold ? 'bg-emerald-100 text-emerald-700' : 'bg-orange-100 text-orange-700' }}">{{ number_format($row['percentage'], 2) }}%</span></td></tr>@empty<tr><td class="px-5 py-12 text-center text-sm text-slate-500" colspan="10">No hay estudiantes para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>
        </article>
    @endif

    @if($reportRiskStudents->isNotEmpty())<article class="rounded-2xl border border-orange-200 bg-orange-50 p-5 dark:border-orange-900 dark:bg-orange-950/20"><p class="text-xs font-black uppercase tracking-wider text-orange-700">Seguimiento prioritario</p><h3 class="mt-1 text-lg font-black">Estudiantes por debajo de {{ $reportRiskThreshold }}%</h3><div class="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($reportRiskStudents as $row)<div class="rounded-xl bg-white p-3 dark:bg-slate-900"><p class="text-sm font-black">{{ $row['student']->nombre }} {{ $row['student']->apellido }}</p><p class="mt-1 text-xs text-slate-500">{{ $row['student']->curso }} · {{ number_format($row['percentage'], 2) }}%</p></div>@endforeach</div></article>@endif

    @if ($selectedReportStudent)
        <article class="overflow-hidden rounded-2xl border border-violet-200 bg-gradient-to-br from-violet-50 to-white shadow-sm dark:border-violet-900 dark:from-violet-950/40 dark:to-slate-900" data-individual-student-report>
            <div class="grid gap-5 p-5 lg:grid-cols-[minmax(0,1.4fr)_repeat(3,minmax(0,.7fr))] lg:items-center"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-violet-600 dark:text-violet-300">Reporte individual de asistencia</p><h2 class="mt-2 text-2xl font-black">{{ $selectedReportStudent->nombre }} {{ $selectedReportStudent->apellido }}</h2><p class="mt-1 text-sm text-slate-500">{{ $selectedReportStudent->matricula }} · {{ $selectedReportStudent->curso }}</p></div>@foreach ([['Días con asistencia', $reportStudentSummary['attendance_days'], 'text-emerald-600'], ['Tardanzas', $reportStudentSummary['late_days'], 'text-amber-600'], ['Días sin entrada', $reportStudentSummary['days_without_entry'], 'text-rose-600']] as [$label, $value, $color])<div class="rounded-2xl border border-white/70 bg-white/80 p-4 dark:border-slate-700 dark:bg-slate-900/70"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black {{ $color }}">{{ $value }}</p></div>@endforeach</div>
            <div class="border-t border-violet-100 p-5 dark:border-violet-900"><h3 class="text-sm font-black">Historial de clases por fecha</h3><div class="mt-3 flex gap-2 overflow-x-auto pb-2">@forelse($reportStudentClassHistory as $item)<article class="min-w-36 rounded-xl border border-violet-100 bg-white p-3 text-center dark:border-violet-900 dark:bg-slate-900"><p class="text-[10px] font-black uppercase text-slate-400">{{ $item['date']->format('d/m/Y') }}</p><p class="mt-2 text-2xl font-black {{ $item['status'] === 'P' ? 'text-emerald-600' : ($item['status'] === 'T' ? 'text-amber-600' : ($item['status'] === 'E' ? 'text-sky-600' : 'text-rose-600')) }}">{{ $item['status'] }}</p><p class="mt-1 truncate text-[10px] text-slate-500" title="{{ $item['subject'] }}">{{ $item['subject'] }}</p><p class="mt-1 text-[9px] text-slate-400">{{ $item['teacher'] }}</p></article>@empty<p class="text-xs text-slate-500">No hay clases registradas en este período.</p>@endforelse</div></div>
            <p class="border-t border-violet-100 px-5 py-3 text-[11px] text-slate-500 dark:border-violet-900">“Días sin entrada” cuenta los días de lunes a viernes del período sin un registro de entrada. Feriados o días no lectivos deben verificarse con el calendario escolar.</p>
        </article>
    @endif

    <section class="grid grid-cols-2 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm lg:grid-cols-4 dark:border-slate-800 dark:bg-slate-900">
        @foreach ([['Estudiantes activos', $reportSummary['students'], 'text-sky-500'], ['Asistencias', $reportSummary['entries'], 'text-emerald-500'], ['Tardanzas', $reportSummary['late'], 'text-amber-500'], ['Justificaciones', $reportSummary['excused'], 'text-violet-500']] as [$label, $value, $color])
            <article class="border-stone-200 px-5 py-5 even:border-l lg:border-l lg:first:border-l-0 dark:border-slate-800"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black {{ $color }}">{{ number_format($value) }}</p></article>
        @endforeach
    </section>

    <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" data-gender-report>
        <header class="flex flex-col gap-2 border-b border-stone-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-fuchsia-600 dark:text-fuchsia-400">Matrícula oficial</p><h2 class="mt-1 text-lg font-black">Femenino y masculino por curso</h2><p class="mt-1 text-xs text-slate-500">Los estudiantes sin el dato registrado se mantienen separados para no alterar los totales.</p></div><span class="w-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black text-slate-700 dark:bg-slate-800 dark:text-slate-200">Total general: {{ number_format($reportGenderTotals['total']) }}</span></header>
        <div class="overflow-x-auto"><table class="w-full min-w-[640px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Curso</th><th class="px-5 py-3 text-center">Femenino</th><th class="px-5 py-3 text-center">Masculino</th><th class="px-5 py-3 text-center">Sin especificar</th><th class="px-5 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($reportGenderByCourse as $course)<tr><td class="px-5 py-4 font-black">{{ $course['course'] }}</td><td class="px-5 py-4 text-center text-lg font-black text-fuchsia-600 dark:text-fuchsia-300">{{ $course['female'] }}</td><td class="px-5 py-4 text-center text-lg font-black text-sky-600 dark:text-sky-300">{{ $course['male'] }}</td><td class="px-5 py-4 text-center text-sm font-bold text-slate-400">{{ $course['unspecified'] }}</td><td class="px-5 py-4 text-right text-lg font-black">{{ $course['total'] }}</td></tr>@empty<tr><td class="px-5 py-12 text-center text-sm text-slate-500" colspan="5">No hay estudiantes para los filtros seleccionados.</td></tr>@endforelse</tbody>@if ($reportGenderByCourse->isNotEmpty())<tfoot class="border-t-2 border-stone-200 bg-stone-50 font-black dark:border-slate-700 dark:bg-slate-950"><tr><td class="px-5 py-4">Total general</td><td class="px-5 py-4 text-center text-fuchsia-600 dark:text-fuchsia-300">{{ $reportGenderTotals['female'] }}</td><td class="px-5 py-4 text-center text-sky-600 dark:text-sky-300">{{ $reportGenderTotals['male'] }}</td><td class="px-5 py-4 text-center text-slate-400">{{ $reportGenderTotals['unspecified'] }}</td><td class="px-5 py-4 text-right text-xl">{{ $reportGenderTotals['total'] }}</td></tr></tfoot>@endif</table></div>
    </article>

    <section class="grid gap-5 xl:grid-cols-5">
        <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm xl:col-span-3 dark:border-slate-800 dark:bg-slate-900">
            <header class="border-b border-stone-100 px-5 py-4 dark:border-slate-800"><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600 dark:text-teal-400">Comparación</p><h2 class="mt-1 text-lg font-black">Rendimiento por curso</h2></header>
            <div class="overflow-x-auto"><table class="w-full min-w-[620px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Curso</th><th class="px-5 py-3">Estudiantes</th><th class="px-5 py-3">Asistencias</th><th class="px-5 py-3">Tardanzas</th><th class="px-5 py-3 text-right">Puntualidad</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($reportByCourse as $course)<tr><td class="px-5 py-4 font-black">{{ $course['course'] }}</td><td class="px-5 py-4 text-sm text-slate-500">{{ $course['students'] }}</td><td class="px-5 py-4 text-sm font-bold text-emerald-600">{{ $course['entries'] }}</td><td class="px-5 py-4 text-sm font-bold text-amber-600">{{ $course['late'] }}</td><td class="px-5 py-4 text-right"><span class="rounded-full bg-teal-50 px-3 py-1.5 text-xs font-black text-teal-700 dark:bg-teal-400/10 dark:text-teal-300">{{ $course['on_time_percentage'] }}%</span></td></tr>@empty<tr><td class="px-5 py-12 text-center text-sm text-slate-500" colspan="5">No hay datos para el período seleccionado.</td></tr>@endforelse</tbody></table></div>
        </article>

        <article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm xl:col-span-2 dark:border-slate-800 dark:bg-slate-900">
            <header class="border-b border-stone-100 px-5 py-4 dark:border-slate-800"><p class="text-[11px] font-black uppercase tracking-[.18em] text-sky-600 dark:text-sky-400">Tendencia</p><h2 class="mt-1 text-lg font-black">Actividad por día</h2></header>
            <div class="max-h-96 divide-y divide-stone-100 overflow-y-auto dark:divide-slate-800">@forelse ($reportByDay as $day)<div class="flex items-center justify-between gap-4 px-5 py-4"><div><p class="text-sm font-black">{{ $day['date']->locale('es')->isoFormat('dddd D [de] MMMM') }}</p><p class="mt-1 text-xs text-slate-500">{{ $day['late'] }} tardanza{{ $day['late'] === 1 ? '' : 's' }}</p></div><span class="text-2xl font-black text-sky-500">{{ $day['entries'] }}</span></div>@empty<p class="px-5 py-12 text-center text-sm text-slate-500">Sin actividad en este período.</p>@endforelse</div>
        </article>
    </section>

    @if(in_array($reportType, ['general', 'history', 'student'], true))<article class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <header class="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-4 dark:border-slate-800"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-violet-600 dark:text-violet-400">Detalle auditable</p><h2 class="mt-1 text-lg font-black">Registros del período</h2></div><span class="rounded-full bg-stone-100 px-3 py-1.5 text-xs font-black text-slate-600 dark:bg-slate-800 dark:text-slate-300">Últimos {{ $reportRecords->count() }} registros</span></header>
        <div class="overflow-x-auto"><table class="w-full min-w-[820px] text-left"><thead class="bg-stone-50 text-[11px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Fecha y hora</th><th class="px-5 py-3">Estudiante</th><th class="px-5 py-3">Curso</th><th class="px-5 py-3">Movimiento</th><th class="px-5 py-3 text-right">Condición</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($reportRecords as $record)<tr><td class="px-5 py-4 font-mono text-xs font-bold text-slate-500">{{ $record->fecha_hora->format('d/m/Y H:i') }}</td><td class="px-5 py-4"><p class="text-sm font-black">{{ $record->student?->nombre }} {{ $record->student?->apellido }}</p><p class="mt-1 font-mono text-[11px] text-slate-400">{{ $record->matricula }}</p></td><td class="px-5 py-4 text-sm font-semibold">{{ $record->curso }}</td><td class="px-5 py-4"><span class="rounded-full bg-sky-50 px-3 py-1.5 text-xs font-black text-sky-700 dark:bg-sky-400/10 dark:text-sky-300">{{ $record->tipo }}</span></td><td class="px-5 py-4 text-right"><span class="text-xs font-black {{ $record->is_late ? 'text-amber-600' : 'text-emerald-600' }}">{{ $record->is_late ? 'Tardanza' : 'A tiempo' }}</span>@if ($record->excuse_type)<p class="mt-1 text-[11px] text-violet-500">Justificada</p>@endif</td></tr>@empty<tr><td class="px-5 py-14 text-center text-sm text-slate-500" colspan="5">No se encontraron registros para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>
    </article>@endif

            <footer class="grid gap-8 border-t border-dashed border-stone-300 pt-10 text-center text-xs text-slate-500 sm:grid-cols-3 dark:border-slate-700"><div class="border-t border-slate-400 pt-2">Firma del docente</div><div class="border-t border-slate-400 pt-2">Coordinación académica</div><div class="border-t border-slate-400 pt-2">Dirección del centro</div></footer>
        </div>
    </dialog>
</section>
