@php
    $setting = $settingsSchool->notificationSetting;
    $entryTime = $settingsSchool->attendance_entry_time?->copy() ?? now()->setTime(8, 0);
    $exitTime = $settingsSchool->attendance_exit_time?->copy() ?? now()->setTime(14, 0);
    $lateAt = $entryTime->copy()->addMinutes($settingsSchool->attendance_late_grace_minutes + 1);
    $inputClass = 'mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-3 py-3 text-sm outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-500/10 dark:border-slate-700 dark:bg-slate-950';
@endphp

<section id="settings" class="space-y-5">
    <header class="flex flex-col gap-4 border-b border-stone-200 pb-5 sm:flex-row sm:items-end sm:justify-between dark:border-slate-800">
        <div><p class="text-[11px] font-black uppercase tracking-[.2em] text-teal-500">{{ $settingsSchool->name }}</p><h1 class="mt-1 text-2xl font-black tracking-tight">Configuración</h1><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Horarios, notificaciones y correo institucional del centro.</p></div>
        <nav class="flex flex-wrap gap-2 text-xs font-bold"><a class="rounded-lg bg-stone-100 px-3 py-2 dark:bg-slate-800" href="#schedule-settings">Horarios</a><a class="rounded-lg bg-stone-100 px-3 py-2 dark:bg-slate-800" href="#notification-settings">Notificaciones</a><a class="rounded-lg bg-stone-100 px-3 py-2 dark:bg-slate-800" href="#mail-settings">Correo</a></nav>
    </header>

    <section class="rounded-2xl border border-teal-200 bg-teal-50/70 p-5 shadow-sm dark:border-teal-900 dark:bg-teal-950/20">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-600 dark:text-teal-300">Salidas anticipadas</p><h2 class="mt-1 text-lg font-black">Enlace público de autorizaciones</h2><p class="mt-1 max-w-2xl text-sm text-slate-600 dark:text-slate-400">Permite seleccionar y autorizar varios estudiantes para salir antes del horario. Sin autorización, el segundo ponche anticipado será ignorado.</p></div>
            @if ($settingsSchool->early_departure_token)
                <div class="flex flex-wrap gap-2"><a class="rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-black text-white" href="{{ route('public.early-departures.show', $settingsSchool->early_departure_token) }}" target="_blank" rel="noopener">Abrir panel público</a><button class="rounded-xl border border-teal-300 px-4 py-2.5 text-sm font-black text-teal-800 dark:border-teal-700 dark:text-teal-200" type="button" data-copy-value="{{ route('public.early-departures.show', $settingsSchool->early_departure_token) }}">Copiar enlace</button><form action="{{ route('schools.early-departures.revoke', $settingsSchool) }}" method="POST" data-confirm="¿Revocar este enlace? Dejará de funcionar inmediatamente.">@csrf @method('DELETE')<button class="rounded-xl px-3 py-2.5 text-sm font-black text-rose-600" type="submit">Revocar</button></form></div>
            @else
                <form action="{{ route('schools.early-departures.generate', $settingsSchool) }}" method="POST">@csrf<button class="rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-black text-white" type="submit">Generar enlace público</button></form>
            @endif
        </div>
    </section>

    <div class="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(22rem,.75fr)]">
        <form id="schedule-settings" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900" action="{{ route('schools.settings.update', $settingsSchool) }}" method="POST">
            @csrf @method('PUT')
            <div><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-500">Horarios y asistencia</p><h2 class="mt-1 text-lg font-black">Reglas del plantel</h2><p class="mt-1 text-sm text-slate-500">Define cómo se clasifican los ponches sin alterar el registro original del lector.</p></div>
            <div class="mt-5 grid gap-4 sm:grid-cols-2">
                <label class="text-xs font-bold text-slate-500">Hora de entrada<input class="{{ $inputClass }}" name="attendance_entry_time" type="time" required value="{{ $entryTime->format('H:i') }}"></label>
                <label class="text-xs font-bold text-slate-500">Hora de salida<input class="{{ $inputClass }}" name="attendance_exit_time" type="time" required value="{{ $exitTime->format('H:i') }}"></label>
                <label class="text-xs font-bold text-slate-500">Tolerancia antes de tardanza<input class="{{ $inputClass }}" name="attendance_late_grace_minutes" type="number" min="0" max="180" required value="{{ $settingsSchool->attendance_late_grace_minutes }}"><span class="mt-1 block font-normal">Minutos posteriores a la entrada.</span></label>
                <label class="text-xs font-bold text-slate-500">Intervalo mínimo entre ponches<input class="{{ $inputClass }}" name="attendance_cooldown_minutes" type="number" min="1" max="120" required value="{{ $settingsSchool->attendance_cooldown_minutes }}"><span class="mt-1 block font-normal">Evita duplicados consecutivos.</span></label>
            </div>
            <div class="mt-5 rounded-xl bg-slate-950 p-4 text-slate-100">
                <p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-300">Resumen de reglas actuales</p>
                <dl class="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt class="text-slate-400">Entrada programada</dt><dd class="font-black">{{ $entryTime->format('H:i') }}</dd></div><div><dt class="text-slate-400">La tardanza comienza</dt><dd class="font-black text-amber-300">{{ $lateAt->format('H:i') }}</dd></div><div><dt class="text-slate-400">Salida programada</dt><dd class="font-black">{{ $exitTime->format('H:i') }}</dd></div><div><dt class="text-slate-400">Ponche siguiente permitido</dt><dd class="font-black">{{ $settingsSchool->attendance_cooldown_minutes }} min después</dd></div></dl>
            </div>
            <div class="mt-4 grid gap-2 rounded-xl border border-stone-200 p-4 dark:border-slate-700 sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><div><p class="text-[10px] font-black tracking-widest text-teal-500">PRIMER PONCHE</p><p class="mt-1 font-black">Entrada</p></div><span class="self-center text-slate-400">→</span><div><p class="text-[10px] font-black tracking-widest text-teal-500">INTERVALO</p><p class="mt-1 font-black">{{ $settingsSchool->attendance_cooldown_minutes }} minutos</p></div><span class="self-center text-slate-400">→</span><div><p class="text-[10px] font-black tracking-widest text-teal-500">SIGUIENTE PONCHE</p><p class="mt-1 font-black">Salida</p></div></div>
            <button class="mt-5 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-black text-white hover:bg-teal-500" type="submit">Guardar reglas</button>
        </form>

        <form id="notification-settings" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900" action="{{ route('schools.notifications.update', $settingsSchool) }}" method="POST">
            @csrf @method('PUT')
            <p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-500">Notificaciones</p><h2 class="mt-1 text-lg font-black">Eventos y destinatarios</h2><p class="mt-1 text-sm text-slate-500">Estas preferencias solo afectan a {{ $settingsSchool->short_name ?: $settingsSchool->name }}.</p>
            <label class="mt-5 flex items-center justify-between rounded-xl bg-stone-50 p-4 dark:bg-slate-950"><span><strong class="block text-sm">Enviar notificaciones por correo</strong><small class="text-slate-500">Activa o pausa todos los envíos.</small></span><input class="h-5 w-5 accent-teal-600" type="checkbox" name="email_enabled" value="1" @checked($setting?->email_enabled)></label>
            <fieldset class="mt-5"><legend class="text-xs font-black uppercase tracking-wider text-slate-500">Eventos</legend><div class="mt-3 space-y-3">@foreach ([['notify_entry', 'Entrada del estudiante', $setting?->notify_entry ?? true], ['notify_exit', 'Salida del estudiante', $setting?->notify_exit ?? true], ['notify_early_departure', 'Salida anticipada', $setting?->notify_early_departure ?? true]] as [$name, $label, $checked])<label class="flex items-center gap-3 text-sm font-bold"><input class="h-4 w-4 accent-teal-600" type="checkbox" name="{{ $name }}" value="1" @checked($checked)>{{ $label }}</label>@endforeach</div></fieldset>
            <fieldset class="mt-5 border-t border-stone-200 pt-5 dark:border-slate-800"><legend class="text-xs font-black uppercase tracking-wider text-slate-500">Destinatarios</legend><div class="mt-3 space-y-3">@foreach ([['send_to_father', 'Correo del padre', $setting?->send_to_father ?? true], ['send_to_mother', 'Correo de la madre', $setting?->send_to_mother ?? true]] as [$name, $label, $checked])<label class="flex items-center gap-3 text-sm font-bold"><input class="h-4 w-4 accent-teal-600" type="checkbox" name="{{ $name }}" value="1" @checked($checked)>{{ $label }}</label>@endforeach</div></fieldset>
            <button class="mt-5 w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-black text-white dark:bg-teal-600" type="submit">Guardar notificaciones</button>
        </form>
    </div>

    <section id="mail-settings" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-500">Correo del sistema</p><h2 class="mt-1 text-lg font-black">Servidor SMTP</h2><p class="mt-1 text-sm text-slate-500">La contraseña se almacena cifrada y nunca se vuelve a mostrar.</p></div>
        <div class="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
            <form class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" action="{{ route('schools.mail.update', $settingsSchool) }}" method="POST">@csrf @method('PUT')
                <label class="text-xs font-bold text-slate-500">Proveedor<select class="{{ $inputClass }}" disabled><option>SMTP</option></select></label>
                <label class="text-xs font-bold text-slate-500 sm:col-span-2">Servidor SMTP<input class="{{ $inputClass }}" name="smtp_host" required value="{{ old('smtp_host', $setting?->smtp_host) }}" placeholder="smtp.proveedor.com"></label>
                <label class="text-xs font-bold text-slate-500">Puerto<input class="{{ $inputClass }}" type="number" min="1" max="65535" name="smtp_port" required value="{{ old('smtp_port', $setting?->smtp_port ?? 587) }}"></label>
                <label class="text-xs font-bold text-slate-500">Seguridad<select class="{{ $inputClass }}" name="smtp_security" required>@foreach (['none' => 'Ninguna', 'starttls' => 'STARTTLS', 'ssl_tls' => 'SSL/TLS'] as $value => $label)<option value="{{ $value }}" @selected(old('smtp_security', $setting?->smtp_security ?? 'starttls') === $value)>{{ $label }}</option>@endforeach</select></label>
                <label class="text-xs font-bold text-slate-500">Usuario SMTP<input class="{{ $inputClass }}" name="smtp_username" value="{{ old('smtp_username', $setting?->smtp_username) }}" autocomplete="off"></label>
                <label class="text-xs font-bold text-slate-500">Correo remitente<input class="{{ $inputClass }}" type="email" name="from_address" required value="{{ old('from_address', $setting?->from_address) }}"></label>
                <label class="text-xs font-bold text-slate-500">Nombre del remitente<input class="{{ $inputClass }}" name="from_name" required value="{{ old('from_name', $setting?->from_name ?? $settingsSchool->name) }}"></label>
                <label class="text-xs font-bold text-slate-500">Contraseña<input class="{{ $inputClass }}" type="password" name="smtp_password" autocomplete="new-password" placeholder="{{ $setting?->smtp_password ? 'Guardada · dejar vacío para conservar' : 'Contraseña SMTP' }}"></label>
                <div class="sm:col-span-2 lg:col-span-3"><button class="rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-black text-white" type="submit">Guardar configuración</button></div>
            </form>
            <form class="rounded-xl bg-stone-50 p-4 dark:bg-slate-950" action="{{ route('schools.mail.test', $settingsSchool) }}" method="POST">@csrf<p class="text-sm font-black">Enviar correo de prueba</p><p class="mt-1 text-xs text-slate-500">Introduce un destinatario real bajo tu control.</p><label class="mt-4 block text-xs font-bold text-slate-500">Destinatario<input class="{{ $inputClass }}" type="email" name="test_email" required placeholder="administracion@escuela.edu"></label><button class="mt-4 w-full rounded-xl border border-teal-600 px-4 py-2.5 text-sm font-black text-teal-700 dark:text-teal-300" type="submit">Enviar correo de prueba</button></form>
        </div>
    </section>

    <section class="rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><header class="border-b border-stone-200 p-5 dark:border-slate-800"><p class="text-[11px] font-black uppercase tracking-[.18em] text-teal-500">Auditoría</p><h2 class="mt-1 text-lg font-black">Historial de notificaciones</h2></header><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-stone-50 text-[11px] uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Fecha / hora</th><th class="px-5 py-3">Estudiante</th><th class="px-5 py-3">Evento</th><th class="px-5 py-3">Destinatario</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3">Detalle</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($notificationHistory as $notification)<tr><td class="px-5 py-4 whitespace-nowrap">{{ $notification->processed_at->format('d/m/Y H:i') }}</td><td class="px-5 py-4 font-bold">{{ $notification->student ? $notification->student->nombre.' '.$notification->student->apellido : 'Sin estudiante' }}</td><td class="px-5 py-4">{{ $notification->event_type }}</td><td class="px-5 py-4">{{ $notification->recipient ?: '—' }}</td><td class="px-5 py-4"><span class="font-black {{ $notification->status === 'Enviado' ? 'text-emerald-600' : ($notification->status === 'Fallido' ? 'text-rose-600' : 'text-amber-600') }}">{{ $notification->status }}</span></td><td class="max-w-xs truncate px-5 py-4 text-slate-500" title="{{ $notification->failure_reason }}">{{ $notification->failure_reason ?: '—' }}</td></tr>@empty<tr><td class="px-5 py-10 text-center text-slate-500" colspan="6">Todavía no hay notificaciones procesadas.</td></tr>@endforelse</tbody></table></div></section>
</section>
