<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consola SaaS | SuperAdmin</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-slate-950 font-sans text-slate-100 antialiased">
    <header class="border-b border-white/10 bg-slate-950/90 backdrop-blur">
        <div class="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-5 sm:px-8">
            <div class="flex items-center gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-400 font-black text-slate-950">SA</span><div><p class="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Infraestructura SaaS</p><h1 class="mt-0.5 text-lg font-black">Consola global del SuperAdmin</h1></div></div>
            <div class="flex items-center gap-3"><span class="hidden text-right text-xs text-slate-400 sm:block">Centros, seguridad y operación técnica</span><form action="{{ route('logout') }}" method="POST">@csrf<button class="rounded-xl border border-white/15 px-4 py-2 text-sm font-bold hover:bg-white/10">Salir</button></form></div>
        </div>
    </header>
    <main class="mx-auto max-w-[1500px] space-y-7 px-5 py-7 sm:px-8">
        @if (session('success'))<div class="rounded-2xl border border-emerald-400/30 bg-emerald-400/10 px-4 py-3 text-sm font-bold text-emerald-200">{{ session('success') }}</div>@endif
        @if ($errors->any())<div class="rounded-2xl border border-rose-400/30 bg-rose-400/10 px-4 py-3 text-sm font-bold text-rose-100">{{ $errors->first() }}</div>@endif

        <section class="overflow-hidden rounded-3xl border border-cyan-400/15 bg-gradient-to-br from-cyan-500/20 via-slate-900 to-slate-950 p-6 shadow-2xl shadow-cyan-950/20 sm:p-8">
            <p class="text-xs font-black uppercase tracking-[.22em] text-cyan-300">Nivel de plataforma</p><div class="mt-3 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><h2 class="max-w-3xl text-3xl font-black tracking-tight sm:text-4xl">Instituciones, acceso y seguridad desde un solo lugar.</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Aquí no se pasa lista ni se administra un curso. Esta consola controla el servicio contratado por cada institución.</p></div><span class="w-fit rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-xs font-black text-cyan-100">SuperAdmin global</span></div>
        </section>

        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach ([['Instituciones', $summary['schools'], 'text-cyan-300'], ['Activas', $summary['activeSchools'], 'text-emerald-300'], ['Suspendidas', $summary['suspendedSchools'], 'text-amber-300'], ['Admins maestros', $summary['administrators'], 'text-violet-300']] as [$label, $value, $color])<article class="rounded-2xl border border-white/10 bg-slate-900 p-5"><p class="text-sm font-bold text-slate-400">{{ $label }}</p><p class="mt-3 text-4xl font-black {{ $color }}">{{ $value }}</p></article>@endforeach</section>

        <section class="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
            <article class="rounded-2xl border border-white/10 bg-slate-900"><div class="border-b border-white/10 px-5 py-5"><p class="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Onboarding</p><h2 class="mt-1 text-xl font-black">Crear institución</h2></div><form class="grid gap-3 p-5 sm:grid-cols-2" action="{{ route('superadmin.schools.store') }}" method="POST">@csrf
                <label class="text-sm font-bold">Código<input class="{{ $input = 'mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400' }}" name="code" required placeholder="COLEGIO001"></label>
                <label class="text-sm font-bold">Nombre<input class="{{ $input }}" name="name" required placeholder="Colegio ejemplo"></label>
                <label class="text-sm font-bold">Nombre corto<input class="{{ $input }}" name="short_name" placeholder="CE"></label>
                <label class="text-sm font-bold">NIT/RUT/Identificación<input class="{{ $input }}" name="tax_id" placeholder="Identificación fiscal"></label>
                <label class="text-sm font-bold">Correo institucional<input class="{{ $input }}" name="email" type="email"></label>
                <label class="text-sm font-bold">Teléfono<input class="{{ $input }}" name="phone"></label>
                <label class="text-sm font-bold sm:col-span-2">Dirección<input class="{{ $input }}" name="address"></label>
                <label class="text-sm font-bold sm:col-span-2">URL del logotipo<input class="{{ $input }}" name="logo_path" type="url" placeholder="https://..."></label>
                <label class="flex items-center gap-3 rounded-xl border border-cyan-300/20 bg-cyan-300/5 px-4 py-3 text-sm font-bold sm:col-span-2"><input class="h-4 w-4" name="active_modules[]" type="checkbox" value="attendance" checked> Activar módulo de asistencia</label>
                <button class="rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-slate-950 sm:col-span-2" type="submit">Crear institución</button>
            </form></article>
            <article class="rounded-2xl border border-white/10 bg-slate-900"><div class="border-b border-white/10 px-5 py-5"><p class="text-xs font-black uppercase tracking-[.18em] text-violet-300">Acceso inicial</p><h2 class="mt-1 text-xl font-black">Crear Admin del centro</h2></div><form class="grid gap-3 p-5" action="{{ route('superadmin.administrators.store') }}" method="POST">@csrf
                <label class="text-sm font-bold">Institución<select class="{{ $input }}" name="school_id" required><option value="">Seleccionar</option>@foreach ($schools as $school)<option value="{{ $school->id }}">{{ $school->code }} · {{ $school->name }}</option>@endforeach</select></label>
                <label class="text-sm font-bold">Nombre<input class="{{ $input }}" name="name" required></label><label class="text-sm font-bold">Usuario<input class="{{ $input }}" name="username" required></label><label class="text-sm font-bold">Correo<input class="{{ $input }}" name="email" type="email" required></label><label class="text-sm font-bold">Contraseña<input class="{{ $input }}" name="password" type="password" minlength="10" required></label><label class="text-sm font-bold">Confirmar contraseña<input class="{{ $input }}" name="password_confirmation" type="password" minlength="10" required></label>
                <button class="rounded-xl bg-violet-400 px-5 py-3 text-sm font-black text-slate-950" type="submit">Crear administrador maestro</button>
            </form></article>
        </section>

        <section class="rounded-2xl border border-white/10 bg-slate-900"><div class="border-b border-white/10 px-5 py-5"><p class="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Multi-tenant</p><h2 class="mt-1 text-xl font-black">Instituciones contratadas</h2></div><div class="grid gap-4 p-5 lg:grid-cols-2">@forelse ($schools as $school)<article class="rounded-2xl border border-white/10 bg-slate-950 p-4"><div class="flex gap-3"><div class="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-cyan-400/15 font-black text-cyan-200">@if ($school->logo_path)<img class="h-full w-full object-cover" src="{{ $school->logo_path }}" alt="Logo">@else{{ strtoupper(substr($school->short_name ?: $school->name, 0, 2)) }}@endif</div><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div><h3 class="font-black">{{ $school->name }}</h3><p class="mt-1 text-xs text-slate-400">{{ $school->code }} · {{ $school->tax_id ?: 'Sin ID fiscal' }}</p></div><span class="rounded-full px-2.5 py-1 text-xs font-black {{ $school->is_active ? 'bg-emerald-400/15 text-emerald-300' : 'bg-amber-400/15 text-amber-300' }}">{{ $school->is_active ? 'Activa' : 'Suspendida' }}</span></div><p class="mt-3 text-xs text-slate-400">{{ $school->students_count }} estudiantes · {{ $school->devices_count }} lectores · {{ $school->users->count() }} admins activos</p></div></div>
                <div class="mt-4 flex flex-wrap gap-2">@forelse ($school->active_modules ?? [] as $module)<span class="rounded-lg bg-cyan-400/10 px-2.5 py-1 text-xs font-bold text-cyan-200">{{ $module === 'attendance' ? 'Asistencia' : $module }}</span>@empty<span class="rounded-lg bg-slate-800 px-2.5 py-1 text-xs font-bold text-slate-400">Sin módulos activos</span>@endforelse</div>
                <details class="mt-4"><summary class="cursor-pointer text-xs font-black text-cyan-300">Gestionar institución</summary><form class="mt-3 grid gap-2 sm:grid-cols-2" action="{{ route('superadmin.schools.update', $school) }}" method="POST">@csrf @method('PUT')<input class="{{ $input }}" name="code" value="{{ $school->code }}" required><input class="{{ $input }}" name="name" value="{{ $school->name }}" required><input class="{{ $input }}" name="short_name" value="{{ $school->short_name }}" placeholder="Nombre corto"><input class="{{ $input }}" name="tax_id" value="{{ $school->tax_id }}" placeholder="NIT/RUT"><input class="{{ $input }}" name="email" value="{{ $school->email }}" type="email" placeholder="Correo"><input class="{{ $input }}" name="phone" value="{{ $school->phone }}" placeholder="Teléfono"><input class="{{ $input }} sm:col-span-2" name="address" value="{{ $school->address }}" placeholder="Dirección"><input class="{{ $input }} sm:col-span-2" name="logo_path" value="{{ $school->logo_path }}" type="url" placeholder="URL logo"><label class="flex items-center gap-2 text-xs font-bold sm:col-span-2"><input name="active_modules[]" type="checkbox" value="attendance" @checked(in_array('attendance', $school->active_modules ?? [], true))> Módulo de asistencia activo</label><button class="rounded-lg bg-cyan-400 px-3 py-2 text-xs font-black text-slate-950" type="submit">Guardar perfil</button></form></details>
                <div class="mt-3 flex flex-wrap gap-2"><form action="{{ route('superadmin.schools.status', $school) }}" method="POST">@csrf @method('PUT')<input name="is_active" type="hidden" value="{{ $school->is_active ? '0' : '1' }}"><button class="rounded-lg px-3 py-2 text-xs font-black {{ $school->is_active ? 'bg-amber-400/15 text-amber-200' : 'bg-emerald-400/15 text-emerald-200' }}" type="submit">{{ $school->is_active ? 'Suspender plataforma' : 'Reactivar plataforma' }}</button></form><a class="rounded-lg bg-slate-800 px-3 py-2 text-xs font-black text-slate-200" href="{{ route('superadmin.schools.backup', $school) }}">Descargar respaldo cifrado</a></div>
                @foreach ($school->users as $administrator)<details class="mt-3 rounded-xl border border-white/10 p-3"><summary class="cursor-pointer text-xs font-bold text-slate-300">Restablecer clave · {{ $administrator->name }} ({{ $administrator->username }})</summary><form class="mt-2 grid gap-2 sm:grid-cols-2" action="{{ route('superadmin.administrators.password', $administrator) }}" method="POST">@csrf @method('PUT')<input class="{{ $input }}" name="password" type="password" minlength="10" placeholder="Nueva contraseña" required><input class="{{ $input }}" name="password_confirmation" type="password" minlength="10" placeholder="Confirmar" required><button class="rounded-lg bg-violet-400 px-3 py-2 text-xs font-black text-slate-950" type="submit">Restablecer</button></form></details>@endforeach
            </article>@empty<p class="text-sm text-slate-400">Aún no hay instituciones creadas.</p>@endforelse</div></section>

        <section class="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><article class="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5"><p class="text-xs font-black uppercase tracking-[.18em] text-amber-300">Mantenimiento y actualizaciones</p><h2 class="mt-2 text-xl font-black">Despliegue controlado</h2><p class="mt-3 text-sm leading-6 text-slate-300">Las actualizaciones de software se aplican desde el proceso de despliegue, nunca desde un botón web. Así se evita actualizar código sin respaldo, sin revisión o mientras los lectores están reportando.</p><p class="mt-4 text-xs font-bold text-amber-200">Antes de cada actualización: descarga el respaldo cifrado y registra el cambio en la auditoría.</p></article><article class="overflow-hidden rounded-2xl border border-white/10 bg-slate-900"><div class="border-b border-white/10 px-5 py-5"><p class="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Auditoría técnica</p><h2 class="mt-1 text-xl font-black">Acciones recientes</h2></div><div class="max-h-80 overflow-y-auto divide-y divide-white/10">@forelse ($logs as $log)<div class="px-5 py-4"><div class="flex justify-between gap-4"><div><p class="text-sm font-bold">{{ $log->description }}</p><p class="mt-1 text-xs text-slate-400">{{ $log->actor?->username ?? 'Sistema' }} · {{ $log->school?->code ?? 'Global' }} · IP {{ $log->ip_address ?? '—' }}</p></div><time class="shrink-0 text-xs text-slate-500">{{ $log->created_at->format('d/m H:i') }}</time></div></div>@empty<div class="px-5 py-10 text-center text-sm text-slate-400">Todavía no hay acciones auditadas.</div>@endforelse</div></article></section>
    </main>
</body>
</html>
