<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="color-scheme" content="light dark">
    <title>Panel docente | {{ $teacher->school?->name ?? 'Portal escolar' }}</title>
    <script>(()=>{const t=localStorage.getItem('school-panel-theme');document.documentElement.classList.toggle('dark',t==='dark'||(!t&&matchMedia('(prefers-color-scheme: dark)').matches))})();</script>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-stone-50 text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100">
<div class="min-h-screen lg:grid lg:grid-cols-[17rem_minmax(0,1fr)]">
    <aside class="hidden border-r border-teal-900 bg-teal-950 text-white lg:sticky lg:top-0 lg:flex lg:h-screen lg:flex-col">
        <div class="border-b border-white/10 p-6"><a class="flex items-center gap-3" href="{{ route('dashboard.docente') }}"><span class="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-300 text-xl font-black text-teal-950">A</span><span><strong class="block">Aula activa</strong><small class="text-[10px] font-bold uppercase tracking-[.2em] text-teal-300">Panel docente</small></span></a></div>
        <nav class="flex-1 space-y-2 p-4 text-sm font-bold text-teal-100/70"><a class="block rounded-xl bg-white/10 px-4 py-3 text-white" href="#today">Mis clases de hoy</a><a class="block rounded-xl px-4 py-3 hover:bg-white/10 hover:text-white" href="#roster">Tomar asistencia</a><a class="block rounded-xl px-4 py-3 hover:bg-white/10 hover:text-white" href="#reports">Incidencias reportadas</a></nav>
        <div class="p-4"><div class="rounded-2xl border border-white/10 bg-white/5 p-4"><p class="text-xs font-black uppercase tracking-wider text-teal-300">Regla del sistema</p><p class="mt-2 text-xs leading-5 text-teal-100/70">La huella confirma el plantel. Tú confirmas la presencia dentro del aula.</p></div></div>
    </aside>
    <div class="min-w-0">
        <header class="sticky top-0 z-30 border-b border-stone-200/80 bg-stone-50/90 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/90"><div class="flex h-20 items-center justify-between gap-3 px-4 sm:px-8"><div class="min-w-0"><p class="truncate text-sm font-black">{{ $teacher->school?->name ?? 'Centro educativo' }}</p><p class="truncate text-xs text-slate-500">{{ $teacher->name }} · Docente</p></div><div class="flex gap-2"><button data-theme-toggle class="h-10 w-10 rounded-xl border border-stone-200 bg-white dark:border-slate-700 dark:bg-slate-900" type="button" aria-label="Cambiar tema">◐</button><form action="{{ route('logout') }}" method="POST">@csrf<button class="rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-xs font-bold dark:border-slate-700 dark:bg-slate-900">Salir</button></form></div></div></header>
        <main class="mx-auto max-w-[1500px] space-y-6 p-4 sm:p-8">
            @if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-bold text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200">{{ session('success') }}</div>@endif
            @if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-800"><p class="font-black">No se pudo guardar:</p><ul class="mt-2 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <section id="today" class="rounded-3xl bg-gradient-to-br from-teal-900 via-teal-800 to-cyan-900 p-5 text-white shadow-xl sm:p-8"><div class="grid gap-6 xl:grid-cols-[1fr_auto] xl:items-end"><div><span class="rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em]">Mis clases de hoy</span><h1 class="mt-4 text-3xl font-black sm:text-4xl">Registro de asistencia en aula</h1><p class="mt-2 max-w-2xl text-sm text-teal-100/75">¿Quién está realmente en tu clase? Valida la lista completa sin perder de vista el último registro biométrico.</p></div><form class="grid gap-3 rounded-2xl border border-white/10 bg-white/10 p-4 sm:grid-cols-[minmax(12rem,1fr)_auto_auto]" action="{{ route('dashboard.docente') }}"><label class="text-xs font-bold">Curso<select class="mt-1.5 w-full rounded-xl border-white/10 bg-teal-950 px-3 py-2.5 text-sm" name="course">@forelse($courses as $course)<option value="{{ $course->id }}" @selected($selectedCourse?->id === $course->id)>{{ $course->name }}</option>@empty<option>Sin cursos asignados</option>@endforelse</select></label><label class="text-xs font-bold">Fecha<input class="mt-1.5 w-full rounded-xl border-white/10 bg-teal-950 px-3 py-2.5 text-sm" type="date" name="date" value="{{ $selectedDate->toDateString() }}"></label><button class="self-end rounded-xl bg-amber-300 px-4 py-2.5 text-sm font-black text-teal-950">Consultar</button></form></div></section>
            @if($selectedCourse)
                <section class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-teal-700 dark:text-teal-300">{{ $selectedCourse->code }}</p><h2 class="mt-1 text-xl font-black">{{ $selectedCourse->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $classSession?->subject ?: 'Asistencia del curso' }} · {{ $selectedDate->locale('es')->isoFormat('dddd D [de] MMMM') }} · {{ $summary['students'] }} estudiantes</p></div>@if(!$classSession || $classSession->status === 'closed')<form action="{{ route('teacher.sessions.start') }}" method="POST">@csrf<input type="hidden" name="course_id" value="{{ $selectedCourse->id }}"><button class="rounded-xl bg-teal-700 px-5 py-3 text-sm font-black text-white">{{ $classSession ? 'Editar asistencia' : 'Tomar asistencia' }}</button></form>@else<span class="w-fit rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-black text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300">● Registro en curso</span>@endif</div></section>
                <section id="roster" data-attendance-panel class="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
                    <div class="border-b border-stone-100 p-5 dark:border-slate-800 sm:p-6"><div class="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-teal-700 dark:text-teal-300">Validación directa</p><h2 class="mt-1 text-2xl font-black">Lista de estudiantes</h2><p class="mt-1 text-sm text-slate-500">El estado biométrico no marca automáticamente la asistencia en clase.</p></div>@if($classSession && $classSession->status === 'open')<button data-mark-all class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm font-black text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-300" type="button">✓ Marcar todos presentes</button>@endif</div>
                        <div class="mt-5 flex flex-wrap gap-2">@foreach([['all','Todos',$summary['students']],['present','Presentes',$summary['present']],['absent','Ausentes',$roster->filter(fn($r)=>in_array($r['verification']?->status,['campus_absent_class','absent_campus','excused'],true))->count()],['late','Tardanzas',$roster->filter(fn($r)=>$r['verification']?->status==='late')->count()],['pending','Pendientes',$summary['pending']]] as [$filter,$label,$count])<button data-filter="{{ $filter }}" class="rounded-full border px-3.5 py-2 text-xs font-black {{ $filter==='all'?'border-teal-700 bg-teal-700 text-white':'border-stone-200 bg-white text-slate-600 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-300' }}" type="button">{{ $label }} <span data-filter-count="{{ $filter }}">{{ $count }}</span></button>@endforeach</div>
                    </div>
                    @if($classSession && $classSession->status === 'open')<form action="{{ route('teacher.verifications.roster') }}" method="POST">@csrf<input type="hidden" name="class_session_id" value="{{ $classSession->id }}">@endif
                    <div class="hidden grid-cols-[minmax(14rem,1fr)_minmax(12rem,.7fr)_minmax(24rem,1.25fr)] gap-4 border-b bg-stone-50 px-6 py-3 text-[11px] font-black uppercase tracking-wider text-slate-400 dark:border-slate-800 dark:bg-slate-950/60 lg:grid"><span>Estudiante</span><span>Registro biométrico</span><span>Asistencia en clase</span></div>
                    <div class="divide-y divide-stone-100 dark:divide-slate-800">
                    @forelse($roster as $row)
                        @php
                            $student=$row['student']; $verification=$row['verification'];
                            $campusMeta=match($row['campus_status']){'on_campus'=>['En el plantel','bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300'],'left_campus'=>['Salió del plantel','bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300'],default=>['Sin ponche','bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-300']};
                            $selectedStatus=match($verification?->status){'present'=>'present','late'=>'late','campus_absent_class','absent_campus','excused'=>'absent',default=>'pending'};
                        @endphp
                        <article data-student-row data-status="{{ $selectedStatus }}" class="grid gap-4 px-4 py-4 sm:px-6 lg:grid-cols-[minmax(14rem,1fr)_minmax(12rem,.7fr)_minmax(24rem,1.25fr)] lg:items-center">
                            <div class="flex min-w-0 items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-teal-100 text-sm font-black text-teal-700 dark:bg-teal-400/15 dark:text-teal-300">{{ strtoupper(substr($student->nombre,0,1).substr($student->apellido,0,1)) }}</span><div class="min-w-0"><h3 class="truncate text-sm font-black">{{ $student->nombre }} {{ $student->apellido }}</h3><p class="truncate text-xs text-slate-500">{{ $student->matricula }} · ID {{ $student->id_lector }}</p></div></div>
                            <div><span class="inline-flex rounded-full px-2.5 py-1 text-[11px] font-black {{ $campusMeta[1] }}">{{ $campusMeta[0] }}</span><p class="mt-1.5 text-xs text-slate-500">{{ $row['campus_time']?'Último registro '.$row['campus_time']->format('H:i'):'Sin registro hoy' }}</p></div>
                            @if($classSession && $classSession->status === 'open')<div class="grid grid-cols-3 gap-2"><input data-attendance-input type="hidden" name="attendance[{{ $student->id }}]" value="{{ $selectedStatus==='pending'?'':$selectedStatus }}" @disabled($selectedStatus==='pending')>@foreach([['present','✓','Presente'],['absent','✕','Ausente'],['late','◷','Tardanza']] as [$status,$icon,$label])<button data-status-button="{{ $status }}" class="min-h-11 rounded-xl border px-2 py-2 text-xs font-black {{ $selectedStatus===$status?'border-teal-700 bg-teal-700 text-white shadow-sm':'border-stone-200 bg-stone-50 text-slate-600 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-300' }}" type="button" aria-pressed="{{ $selectedStatus===$status?'true':'false' }}">{{ $icon }} {{ $label }}</button>@endforeach</div>@else<span class="w-fit rounded-full bg-stone-100 px-3 py-1.5 text-xs font-black text-slate-600 dark:bg-slate-800 dark:text-slate-300">{{ ['pending'=>'Pendiente','present'=>'Presente','late'=>'Tardanza','absent'=>'Ausente'][$selectedStatus] }}</span>@endif
                        </article>
                    @empty<div class="p-10 text-center text-sm text-slate-500">No hay estudiantes vinculados a este curso.</div>@endforelse
                    <div data-empty-filter class="hidden p-10 text-center text-sm text-slate-500">No hay estudiantes con este estado.</div></div>
                    @if($classSession && $classSession->status === 'open')<div class="sticky bottom-0 flex flex-col gap-3 border-t bg-white/95 p-4 backdrop-blur-xl dark:border-slate-700 dark:bg-slate-900/95 sm:flex-row sm:items-center sm:justify-between sm:px-6"><p class="text-sm text-slate-500"><strong data-save-summary class="text-slate-900 dark:text-white">{{ $summary['verified'] }} de {{ $summary['students'] }}</strong> estudiantes clasificados. Puedes guardar con pendientes.</p><button class="rounded-xl bg-teal-700 px-6 py-3 text-sm font-black text-white" type="submit">Guardar asistencia</button></div></form>@endif
                </section>
                <section id="reports" class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b p-5 dark:border-slate-800"><p class="text-xs font-black uppercase tracking-[.18em] text-rose-600">Seguimiento</p><h2 class="mt-1 text-xl font-black">Estudiantes en el plantel que faltaron a clase</h2></div>@forelse($recentReports as $report)<div class="border-b p-5 dark:border-slate-800"><p class="font-black">{{ $report->student?->nombre }} {{ $report->student?->apellido }}</p><p class="text-sm text-slate-500">{{ $report->classSession?->course?->name }} · {{ $report->verified_at->format('d/m/Y H:i') }}</p></div>@empty<div class="p-10 text-center text-sm text-slate-500">Todavía no hay incidencias de este tipo.</div>@endforelse</section>
            @else<section class="rounded-3xl border border-dashed p-12 text-center"><h2 class="text-xl font-black">Aún no tienes cursos asignados</h2></section>@endif
        </main>
    </div>
</div>
<script>
(()=>{const p=document.querySelector('[data-attendance-panel]');if(!p)return;const rows=Array.from(p.querySelectorAll('[data-student-row]')),filters=Array.from(p.querySelectorAll('[data-filter]')),empty=p.querySelector('[data-empty-filter]');let active='all';const on=['border-teal-700','bg-teal-700','text-white','shadow-sm'],off=['border-stone-200','bg-stone-50','text-slate-600','dark:border-slate-700','dark:bg-slate-950','dark:text-slate-300'];const swap=(element,remove,add)=>{remove.forEach(name=>element.classList.remove(name));add.forEach(name=>element.classList.add(name))};const refresh=()=>{const c={all:rows.length,present:0,absent:0,late:0,pending:0};rows.forEach(r=>c[r.dataset.status]++);Object.entries(c).forEach(([s,n])=>{const t=p.querySelector(`[data-filter-count="${s}"]`);if(t)t.textContent=n});const summary=p.querySelector('[data-save-summary]');if(summary)summary.textContent=`${rows.length-c.pending} de ${rows.length}`;let visible=0;rows.forEach(r=>{const show=active==='all'||r.dataset.status===active;r.classList.toggle('hidden',!show);if(show)visible++});empty?.classList.toggle('hidden',visible>0)};const select=(r,s)=>{r.dataset.status=s;const input=r.querySelector('[data-attendance-input]');input.disabled=false;input.value=s;r.querySelectorAll('[data-status-button]').forEach(b=>{const yes=b.dataset.statusButton===s;b.setAttribute('aria-pressed',yes?'true':'false');swap(b,yes?off:on,yes?on:off)});refresh()};rows.forEach(r=>r.querySelectorAll('[data-status-button]').forEach(b=>b.addEventListener('click',()=>select(r,b.dataset.statusButton))));p.querySelector('[data-mark-all]')?.addEventListener('click',()=>rows.forEach(r=>select(r,'present')));filters.forEach(b=>b.addEventListener('click',()=>{active=b.dataset.filter;filters.forEach(x=>{const yes=x===b;x.classList.toggle('border-teal-700',yes);x.classList.toggle('bg-teal-700',yes);x.classList.toggle('text-white',yes);x.classList.toggle('border-stone-200',!yes);x.classList.toggle('bg-white',!yes);x.classList.toggle('text-slate-600',!yes)});refresh()}));refresh()})();
</script>
</body>
</html>
