<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualización de asistencia | {{ $viewer->school?->name }}</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-stone-50 font-sans text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100">
    <header class="border-b border-teal-900/20 bg-teal-950 text-white"><div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-5 sm:px-8"><div><p class="text-xs font-black uppercase tracking-[.2em] text-teal-300">Consulta institucional</p><h1 class="mt-1 text-xl font-black">Asistencia · {{ $viewer->school?->name }}</h1><p class="mt-1 text-sm text-teal-100/70">Panel de visualización — {{ $viewer->name }}</p></div><form action="{{ route('logout') }}" method="POST">@csrf<button class="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold hover:bg-white/10">Salir</button></form></div></header>
    <main class="mx-auto max-w-7xl space-y-6 px-5 py-7 sm:px-8">
        <form class="grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm md:grid-cols-[11rem_minmax(12rem,1fr)_minmax(12rem,1fr)_auto] dark:border-slate-800 dark:bg-slate-900" method="GET">
            <label class="text-xs font-bold text-slate-500">Día<input class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950" type="date" name="date" value="{{ $date->format('Y-m-d') }}"></label>
            <label class="text-xs font-bold text-slate-500">Curso<select class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950" name="course_id"><option value="">Todos los cursos</option>@foreach ($courses as $course)<option value="{{ $course->id }}" @selected($courseId === $course->id)>{{ $course->name }}</option>@endforeach</select></label>
            <label class="text-xs font-bold text-slate-500">Estudiante<input class="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950" name="student" value="{{ $search }}" placeholder="Nombre, matrícula o ID"></label>
            <div class="flex items-end"><button class="w-full rounded-xl bg-teal-700 px-5 py-2.5 text-sm font-black text-white hover:bg-teal-600">Actualizar vista</button></div>
        </form>
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach ([['Estudiantes', $summary['students'], 'text-teal-700'], ['Entradas', $summary['present'], 'text-emerald-700'], ['Sin entrada', $summary['absent'], 'text-rose-700'], ['Eventos del día', $summary['events'], 'text-amber-700']] as [$label, $value, $color])<article class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-sm font-bold text-slate-500">{{ $label }}</p><p class="mt-3 text-4xl font-black {{ $color }}">{{ $value }}</p><p class="mt-3 text-xs text-slate-400">{{ $date->format('d/m/Y') }}</p></article>@endforeach</section>
        <section class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-stone-100 px-5 py-5 dark:border-slate-800"><p class="text-xs font-black uppercase tracking-[.18em] text-teal-700 dark:text-teal-300">Actividad filtrada</p><h2 class="mt-1 text-xl font-black">Registros de asistencia</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-stone-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-4">Hora</th><th class="px-5 py-4">Estudiante</th><th class="px-5 py-4">Curso</th><th class="px-5 py-4">Tipo</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-slate-800">@forelse ($events as $event)<tr><td class="px-5 py-4 font-mono font-bold text-teal-700">{{ $event->fecha_hora->format('H:i:s') }}</td><td class="px-5 py-4"><p class="font-bold">{{ $event->student?->nombre }} {{ $event->student?->apellido }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->student?->matricula }}</p></td><td class="px-5 py-4">{{ $event->student?->curso ?? $event->curso }}</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-black {{ $event->tipo === 'Entrada' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700' }}">{{ $event->tipo }}</span></td></tr>@empty<tr><td class="px-5 py-12 text-center text-slate-500" colspan="4">No hay registros para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div></section>
    </main>
</body>
</html>
